// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_io_array_io,hls_ip_2022_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.581000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1165,HLS_SYN_LUT=2029,HLS_VERSION=2022_1}" *)

module array_io (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_o_0_din,
        d_o_0_full_n,
        d_o_0_write,
        d_o_1_din,
        d_o_1_full_n,
        d_o_1_write,
        d_o_2_din,
        d_o_2_full_n,
        d_o_2_write,
        d_o_3_din,
        d_o_3_full_n,
        d_o_3_write,
        d_o_4_din,
        d_o_4_full_n,
        d_o_4_write,
        d_o_5_din,
        d_o_5_full_n,
        d_o_5_write,
        d_o_6_din,
        d_o_6_full_n,
        d_o_6_write,
        d_o_7_din,
        d_o_7_full_n,
        d_o_7_write,
        d_i_0_dout,
        d_i_0_empty_n,
        d_i_0_read,
        d_i_1_dout,
        d_i_1_empty_n,
        d_i_1_read,
        d_i_2_dout,
        d_i_2_empty_n,
        d_i_2_read,
        d_i_3_dout,
        d_i_3_empty_n,
        d_i_3_read,
        d_i_4_dout,
        d_i_4_empty_n,
        d_i_4_read,
        d_i_5_dout,
        d_i_5_empty_n,
        d_i_5_read,
        d_i_6_dout,
        d_i_6_empty_n,
        d_i_6_read,
        d_i_7_dout,
        d_i_7_empty_n,
        d_i_7_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] d_o_0_din;
input   d_o_0_full_n;
output   d_o_0_write;
output  [15:0] d_o_1_din;
input   d_o_1_full_n;
output   d_o_1_write;
output  [15:0] d_o_2_din;
input   d_o_2_full_n;
output   d_o_2_write;
output  [15:0] d_o_3_din;
input   d_o_3_full_n;
output   d_o_3_write;
output  [15:0] d_o_4_din;
input   d_o_4_full_n;
output   d_o_4_write;
output  [15:0] d_o_5_din;
input   d_o_5_full_n;
output   d_o_5_write;
output  [15:0] d_o_6_din;
input   d_o_6_full_n;
output   d_o_6_write;
output  [15:0] d_o_7_din;
input   d_o_7_full_n;
output   d_o_7_write;
input  [15:0] d_i_0_dout;
input   d_i_0_empty_n;
output   d_i_0_read;
input  [15:0] d_i_1_dout;
input   d_i_1_empty_n;
output   d_i_1_read;
input  [15:0] d_i_2_dout;
input   d_i_2_empty_n;
output   d_i_2_read;
input  [15:0] d_i_3_dout;
input   d_i_3_empty_n;
output   d_i_3_read;
input  [15:0] d_i_4_dout;
input   d_i_4_empty_n;
output   d_i_4_read;
input  [15:0] d_i_5_dout;
input   d_i_5_empty_n;
output   d_i_5_read;
input  [15:0] d_i_6_dout;
input   d_i_6_empty_n;
output   d_i_6_read;
input  [15:0] d_i_7_dout;
input   d_i_7_empty_n;
output   d_i_7_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] d_o_0_din;
reg d_o_0_write;
reg[15:0] d_o_1_din;
reg d_o_1_write;
reg[15:0] d_o_2_din;
reg d_o_2_write;
reg[15:0] d_o_3_din;
reg d_o_3_write;
reg[15:0] d_o_4_din;
reg d_o_4_write;
reg[15:0] d_o_5_din;
reg d_o_5_write;
reg[15:0] d_o_6_din;
reg d_o_6_write;
reg[15:0] d_o_7_din;
reg d_o_7_write;
reg d_i_0_read;
reg d_i_1_read;
reg d_i_2_read;
reg d_i_3_read;
reg d_i_4_read;
reg d_i_5_read;
reg d_i_6_read;
reg d_i_7_read;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] acc_0;
reg   [31:0] acc_1;
reg   [31:0] acc_2;
reg   [31:0] acc_3;
reg   [31:0] acc_4;
reg   [31:0] acc_5;
reg   [31:0] acc_6;
reg   [31:0] acc_7;
reg    d_o_0_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    d_o_1_blk_n;
reg    d_o_2_blk_n;
reg    d_o_3_blk_n;
reg    d_o_4_blk_n;
reg    d_o_5_blk_n;
reg    d_o_6_blk_n;
reg    d_o_7_blk_n;
reg    d_i_0_blk_n;
reg    d_i_1_blk_n;
reg    d_i_2_blk_n;
reg    d_i_3_blk_n;
reg    d_i_4_blk_n;
reg    d_i_5_blk_n;
reg    d_i_6_blk_n;
reg    d_i_7_blk_n;
reg  signed [15:0] d_i_0_read_reg_804;
reg  signed [15:0] d_i_1_read_reg_810;
reg  signed [15:0] d_i_2_read_reg_816;
reg  signed [15:0] d_i_3_read_reg_822;
reg  signed [15:0] d_i_4_read_reg_828;
reg  signed [15:0] d_i_5_read_reg_834;
reg  signed [15:0] d_i_6_read_reg_840;
reg  signed [15:0] d_i_7_read_reg_846;
wire   [15:0] add_ln69_fu_180_p2;
reg   [15:0] add_ln69_reg_855;
wire   [15:0] add_ln69_1_fu_194_p2;
reg   [15:0] add_ln69_1_reg_863;
wire   [15:0] add_ln69_2_fu_208_p2;
reg   [15:0] add_ln69_2_reg_871;
wire   [15:0] add_ln69_3_fu_222_p2;
reg   [15:0] add_ln69_3_reg_879;
wire   [15:0] add_ln69_4_fu_236_p2;
reg   [15:0] add_ln69_4_reg_887;
wire   [15:0] add_ln69_5_fu_250_p2;
reg   [15:0] add_ln69_5_reg_895;
wire   [15:0] add_ln69_6_fu_264_p2;
reg   [15:0] add_ln69_6_reg_903;
wire   [15:0] add_ln69_7_fu_278_p2;
reg   [15:0] add_ln69_7_reg_911;
reg  signed [15:0] d_i_0_read_1_reg_916;
reg  signed [15:0] d_i_1_read_1_reg_922;
reg  signed [15:0] d_i_2_read_1_reg_928;
reg  signed [15:0] d_i_3_read_1_reg_934;
reg  signed [15:0] d_i_4_read_1_reg_940;
reg  signed [15:0] d_i_5_read_1_reg_946;
reg  signed [15:0] d_i_6_read_1_reg_952;
reg  signed [15:0] d_i_7_read_1_reg_958;
wire   [15:0] add_ln69_8_fu_284_p2;
reg   [15:0] add_ln69_8_reg_964;
wire   [15:0] add_ln69_9_fu_289_p2;
reg   [15:0] add_ln69_9_reg_969;
wire   [15:0] add_ln69_10_fu_294_p2;
reg   [15:0] add_ln69_10_reg_974;
wire   [15:0] add_ln69_11_fu_299_p2;
reg   [15:0] add_ln69_11_reg_979;
wire   [15:0] add_ln69_12_fu_304_p2;
reg   [15:0] add_ln69_12_reg_984;
wire   [15:0] add_ln69_13_fu_309_p2;
reg   [15:0] add_ln69_13_reg_989;
wire   [15:0] add_ln69_14_fu_314_p2;
reg   [15:0] add_ln69_14_reg_994;
wire   [15:0] add_ln69_15_fu_319_p2;
reg   [15:0] add_ln69_15_reg_999;
reg  signed [15:0] d_i_0_read_2_reg_1004;
reg  signed [15:0] d_i_1_read_2_reg_1010;
reg  signed [15:0] d_i_2_read_2_reg_1016;
reg  signed [15:0] d_i_3_read_2_reg_1022;
reg  signed [15:0] d_i_4_read_2_reg_1028;
reg  signed [15:0] d_i_5_read_2_reg_1034;
reg  signed [15:0] d_i_6_read_2_reg_1040;
reg  signed [15:0] d_i_7_read_2_reg_1046;
wire   [16:0] add_ln67_1_fu_392_p2;
reg   [16:0] add_ln67_1_reg_1052;
wire   [15:0] add_ln69_24_fu_398_p2;
reg   [15:0] add_ln69_24_reg_1057;
wire   [16:0] add_ln67_5_fu_408_p2;
reg   [16:0] add_ln67_5_reg_1062;
wire   [15:0] add_ln69_25_fu_414_p2;
reg   [15:0] add_ln69_25_reg_1067;
wire   [16:0] add_ln67_9_fu_424_p2;
reg   [16:0] add_ln67_9_reg_1072;
wire   [15:0] add_ln69_26_fu_430_p2;
reg   [15:0] add_ln69_26_reg_1077;
wire   [16:0] add_ln67_13_fu_440_p2;
reg   [16:0] add_ln67_13_reg_1082;
wire   [15:0] add_ln69_27_fu_446_p2;
reg   [15:0] add_ln69_27_reg_1087;
wire   [16:0] add_ln67_17_fu_456_p2;
reg   [16:0] add_ln67_17_reg_1092;
wire   [15:0] add_ln69_28_fu_462_p2;
reg   [15:0] add_ln69_28_reg_1097;
wire   [16:0] add_ln67_21_fu_472_p2;
reg   [16:0] add_ln67_21_reg_1102;
wire   [15:0] add_ln69_29_fu_478_p2;
reg   [15:0] add_ln69_29_reg_1107;
wire   [16:0] add_ln67_25_fu_488_p2;
reg   [16:0] add_ln67_25_reg_1112;
wire   [15:0] add_ln69_30_fu_494_p2;
reg   [15:0] add_ln69_30_reg_1117;
wire   [16:0] add_ln67_29_fu_504_p2;
reg   [16:0] add_ln67_29_reg_1122;
wire   [15:0] add_ln69_31_fu_510_p2;
reg   [15:0] add_ln69_31_reg_1127;
wire   [31:0] temp_fu_582_p2;
reg    ap_block_state5;
wire   [31:0] temp_1_fu_612_p2;
wire   [31:0] temp_2_fu_642_p2;
wire   [31:0] temp_3_fu_672_p2;
wire   [31:0] temp_4_fu_702_p2;
wire   [31:0] temp_5_fu_732_p2;
wire   [31:0] temp_6_fu_762_p2;
wire   [31:0] temp_7_fu_792_p2;
reg    ap_block_state1;
reg    ap_block_state2;
reg    ap_block_state3;
reg    ap_block_state4;
wire   [15:0] add_ln69_16_fu_327_p2;
wire   [15:0] add_ln69_17_fu_335_p2;
wire   [15:0] add_ln69_18_fu_343_p2;
wire   [15:0] add_ln69_19_fu_351_p2;
wire   [15:0] add_ln69_20_fu_359_p2;
wire   [15:0] add_ln69_21_fu_367_p2;
wire   [15:0] add_ln69_22_fu_375_p2;
wire   [15:0] add_ln69_23_fu_383_p2;
wire   [15:0] trunc_ln67_fu_176_p1;
wire   [15:0] trunc_ln67_1_fu_190_p1;
wire   [15:0] trunc_ln67_2_fu_204_p1;
wire   [15:0] trunc_ln67_3_fu_218_p1;
wire   [15:0] trunc_ln67_4_fu_232_p1;
wire   [15:0] trunc_ln67_5_fu_246_p1;
wire   [15:0] trunc_ln67_6_fu_260_p1;
wire   [15:0] trunc_ln67_7_fu_274_p1;
wire  signed [15:0] sext_ln67_8_fu_388_p0;
wire  signed [16:0] sext_ln69_8_fu_324_p1;
wire  signed [16:0] sext_ln67_8_fu_388_p1;
wire  signed [15:0] add_ln69_24_fu_398_p0;
wire  signed [15:0] sext_ln67_11_fu_404_p0;
wire  signed [16:0] sext_ln69_9_fu_332_p1;
wire  signed [16:0] sext_ln67_11_fu_404_p1;
wire  signed [15:0] add_ln69_25_fu_414_p0;
wire  signed [15:0] sext_ln67_14_fu_420_p0;
wire  signed [16:0] sext_ln69_10_fu_340_p1;
wire  signed [16:0] sext_ln67_14_fu_420_p1;
wire  signed [15:0] add_ln69_26_fu_430_p0;
wire  signed [15:0] sext_ln67_17_fu_436_p0;
wire  signed [16:0] sext_ln69_11_fu_348_p1;
wire  signed [16:0] sext_ln67_17_fu_436_p1;
wire  signed [15:0] add_ln69_27_fu_446_p0;
wire  signed [15:0] sext_ln67_20_fu_452_p0;
wire  signed [16:0] sext_ln69_12_fu_356_p1;
wire  signed [16:0] sext_ln67_20_fu_452_p1;
wire  signed [15:0] add_ln69_28_fu_462_p0;
wire  signed [15:0] sext_ln67_23_fu_468_p0;
wire  signed [16:0] sext_ln69_13_fu_364_p1;
wire  signed [16:0] sext_ln67_23_fu_468_p1;
wire  signed [15:0] add_ln69_29_fu_478_p0;
wire  signed [15:0] sext_ln67_26_fu_484_p0;
wire  signed [16:0] sext_ln69_14_fu_372_p1;
wire  signed [16:0] sext_ln67_26_fu_484_p1;
wire  signed [15:0] add_ln69_30_fu_494_p0;
wire  signed [15:0] sext_ln67_29_fu_500_p0;
wire  signed [16:0] sext_ln69_15_fu_380_p1;
wire  signed [16:0] sext_ln67_29_fu_500_p1;
wire  signed [15:0] add_ln69_31_fu_510_p0;
wire  signed [31:0] sext_ln67_fu_516_p1;
wire  signed [17:0] sext_ln67_9_fu_569_p1;
wire  signed [17:0] sext_ln69_fu_540_p1;
wire   [17:0] add_ln67_2_fu_572_p2;
wire  signed [31:0] sext_ln67_10_fu_578_p1;
wire   [31:0] add_ln67_fu_564_p2;
wire  signed [31:0] sext_ln67_1_fu_519_p1;
wire  signed [17:0] sext_ln67_12_fu_599_p1;
wire  signed [17:0] sext_ln69_1_fu_543_p1;
wire   [17:0] add_ln67_6_fu_602_p2;
wire  signed [31:0] sext_ln67_13_fu_608_p1;
wire   [31:0] add_ln67_4_fu_594_p2;
wire  signed [31:0] sext_ln67_2_fu_522_p1;
wire  signed [17:0] sext_ln67_15_fu_629_p1;
wire  signed [17:0] sext_ln69_2_fu_546_p1;
wire   [17:0] add_ln67_10_fu_632_p2;
wire  signed [31:0] sext_ln67_16_fu_638_p1;
wire   [31:0] add_ln67_8_fu_624_p2;
wire  signed [31:0] sext_ln67_3_fu_525_p1;
wire  signed [17:0] sext_ln67_18_fu_659_p1;
wire  signed [17:0] sext_ln69_3_fu_549_p1;
wire   [17:0] add_ln67_14_fu_662_p2;
wire  signed [31:0] sext_ln67_19_fu_668_p1;
wire   [31:0] add_ln67_12_fu_654_p2;
wire  signed [31:0] sext_ln67_4_fu_528_p1;
wire  signed [17:0] sext_ln67_21_fu_689_p1;
wire  signed [17:0] sext_ln69_4_fu_552_p1;
wire   [17:0] add_ln67_18_fu_692_p2;
wire  signed [31:0] sext_ln67_22_fu_698_p1;
wire   [31:0] add_ln67_16_fu_684_p2;
wire  signed [31:0] sext_ln67_5_fu_531_p1;
wire  signed [17:0] sext_ln67_24_fu_719_p1;
wire  signed [17:0] sext_ln69_5_fu_555_p1;
wire   [17:0] add_ln67_22_fu_722_p2;
wire  signed [31:0] sext_ln67_25_fu_728_p1;
wire   [31:0] add_ln67_20_fu_714_p2;
wire  signed [31:0] sext_ln67_6_fu_534_p1;
wire  signed [17:0] sext_ln67_27_fu_749_p1;
wire  signed [17:0] sext_ln69_6_fu_558_p1;
wire   [17:0] add_ln67_26_fu_752_p2;
wire  signed [31:0] sext_ln67_28_fu_758_p1;
wire   [31:0] add_ln67_24_fu_744_p2;
wire  signed [31:0] sext_ln67_7_fu_537_p1;
wire  signed [17:0] sext_ln67_30_fu_779_p1;
wire  signed [17:0] sext_ln69_7_fu_561_p1;
wire   [17:0] add_ln67_30_fu_782_p2;
wire  signed [31:0] sext_ln67_31_fu_788_p1;
wire   [31:0] add_ln67_28_fu_774_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 acc_0 = 32'd0;
#0 acc_1 = 32'd0;
#0 acc_2 = 32'd0;
#0 acc_3 = 32'd0;
#0 acc_4 = 32'd0;
#0 acc_5 = 32'd0;
#0 acc_6 = 32'd0;
#0 acc_7 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_0 <= temp_fu_582_p2;
        acc_1 <= temp_1_fu_612_p2;
        acc_2 <= temp_2_fu_642_p2;
        acc_3 <= temp_3_fu_672_p2;
        acc_4 <= temp_4_fu_702_p2;
        acc_5 <= temp_5_fu_732_p2;
        acc_6 <= temp_6_fu_762_p2;
        acc_7 <= temp_7_fu_792_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln67_13_reg_1082 <= add_ln67_13_fu_440_p2;
        add_ln67_17_reg_1092 <= add_ln67_17_fu_456_p2;
        add_ln67_1_reg_1052 <= add_ln67_1_fu_392_p2;
        add_ln67_21_reg_1102 <= add_ln67_21_fu_472_p2;
        add_ln67_25_reg_1112 <= add_ln67_25_fu_488_p2;
        add_ln67_29_reg_1122 <= add_ln67_29_fu_504_p2;
        add_ln67_5_reg_1062 <= add_ln67_5_fu_408_p2;
        add_ln67_9_reg_1072 <= add_ln67_9_fu_424_p2;
        add_ln69_24_reg_1057 <= add_ln69_24_fu_398_p2;
        add_ln69_25_reg_1067 <= add_ln69_25_fu_414_p2;
        add_ln69_26_reg_1077 <= add_ln69_26_fu_430_p2;
        add_ln69_27_reg_1087 <= add_ln69_27_fu_446_p2;
        add_ln69_28_reg_1097 <= add_ln69_28_fu_462_p2;
        add_ln69_29_reg_1107 <= add_ln69_29_fu_478_p2;
        add_ln69_30_reg_1117 <= add_ln69_30_fu_494_p2;
        add_ln69_31_reg_1127 <= add_ln69_31_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln69_10_reg_974 <= add_ln69_10_fu_294_p2;
        add_ln69_11_reg_979 <= add_ln69_11_fu_299_p2;
        add_ln69_12_reg_984 <= add_ln69_12_fu_304_p2;
        add_ln69_13_reg_989 <= add_ln69_13_fu_309_p2;
        add_ln69_14_reg_994 <= add_ln69_14_fu_314_p2;
        add_ln69_15_reg_999 <= add_ln69_15_fu_319_p2;
        add_ln69_8_reg_964 <= add_ln69_8_fu_284_p2;
        add_ln69_9_reg_969 <= add_ln69_9_fu_289_p2;
        d_i_0_read_2_reg_1004 <= d_i_0_dout;
        d_i_1_read_2_reg_1010 <= d_i_1_dout;
        d_i_2_read_2_reg_1016 <= d_i_2_dout;
        d_i_3_read_2_reg_1022 <= d_i_3_dout;
        d_i_4_read_2_reg_1028 <= d_i_4_dout;
        d_i_5_read_2_reg_1034 <= d_i_5_dout;
        d_i_6_read_2_reg_1040 <= d_i_6_dout;
        d_i_7_read_2_reg_1046 <= d_i_7_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln69_1_reg_863 <= add_ln69_1_fu_194_p2;
        add_ln69_2_reg_871 <= add_ln69_2_fu_208_p2;
        add_ln69_3_reg_879 <= add_ln69_3_fu_222_p2;
        add_ln69_4_reg_887 <= add_ln69_4_fu_236_p2;
        add_ln69_5_reg_895 <= add_ln69_5_fu_250_p2;
        add_ln69_6_reg_903 <= add_ln69_6_fu_264_p2;
        add_ln69_7_reg_911 <= add_ln69_7_fu_278_p2;
        add_ln69_reg_855 <= add_ln69_fu_180_p2;
        d_i_0_read_1_reg_916 <= d_i_0_dout;
        d_i_1_read_1_reg_922 <= d_i_1_dout;
        d_i_2_read_1_reg_928 <= d_i_2_dout;
        d_i_3_read_1_reg_934 <= d_i_3_dout;
        d_i_4_read_1_reg_940 <= d_i_4_dout;
        d_i_5_read_1_reg_946 <= d_i_5_dout;
        d_i_6_read_1_reg_952 <= d_i_6_dout;
        d_i_7_read_1_reg_958 <= d_i_7_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_0_read_reg_804 <= d_i_0_dout;
        d_i_1_read_reg_810 <= d_i_1_dout;
        d_i_2_read_reg_816 <= d_i_2_dout;
        d_i_3_read_reg_822 <= d_i_3_dout;
        d_i_4_read_reg_828 <= d_i_4_dout;
        d_i_5_read_reg_834 <= d_i_5_dout;
        d_i_6_read_reg_840 <= d_i_6_dout;
        d_i_7_read_reg_846 <= d_i_7_dout;
    end
end

always @ (*) begin
    if (((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_0_blk_n = d_i_0_empty_n;
    end else begin
        d_i_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_0_read = 1'b1;
    end else begin
        d_i_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_1_blk_n = d_i_1_empty_n;
    end else begin
        d_i_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_1_read = 1'b1;
    end else begin
        d_i_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_2_blk_n = d_i_2_empty_n;
    end else begin
        d_i_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_2_read = 1'b1;
    end else begin
        d_i_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_3_blk_n = d_i_3_empty_n;
    end else begin
        d_i_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_3_read = 1'b1;
    end else begin
        d_i_3_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_4_blk_n = d_i_4_empty_n;
    end else begin
        d_i_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_4_read = 1'b1;
    end else begin
        d_i_4_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_5_blk_n = d_i_5_empty_n;
    end else begin
        d_i_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_5_read = 1'b1;
    end else begin
        d_i_5_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_6_blk_n = d_i_6_empty_n;
    end else begin
        d_i_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_6_read = 1'b1;
    end else begin
        d_i_6_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_7_blk_n = d_i_7_empty_n;
    end else begin
        d_i_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_7_read = 1'b1;
    end else begin
        d_i_7_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_0_blk_n = d_o_0_full_n;
    end else begin
        d_o_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_0_din = add_ln69_24_reg_1057;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_0_din = add_ln69_16_fu_327_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_0_din = add_ln69_8_fu_284_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_0_din = add_ln69_fu_180_p2;
    end else begin
        d_o_0_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_0_write = 1'b1;
    end else begin
        d_o_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_1_blk_n = d_o_1_full_n;
    end else begin
        d_o_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_1_din = add_ln69_25_reg_1067;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_1_din = add_ln69_17_fu_335_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_1_din = add_ln69_9_fu_289_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_1_din = add_ln69_1_fu_194_p2;
    end else begin
        d_o_1_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_1_write = 1'b1;
    end else begin
        d_o_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_2_blk_n = d_o_2_full_n;
    end else begin
        d_o_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_2_din = add_ln69_26_reg_1077;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_2_din = add_ln69_18_fu_343_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_2_din = add_ln69_10_fu_294_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_2_din = add_ln69_2_fu_208_p2;
    end else begin
        d_o_2_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_2_write = 1'b1;
    end else begin
        d_o_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_3_blk_n = d_o_3_full_n;
    end else begin
        d_o_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_3_din = add_ln69_27_reg_1087;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_3_din = add_ln69_19_fu_351_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_3_din = add_ln69_11_fu_299_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_3_din = add_ln69_3_fu_222_p2;
    end else begin
        d_o_3_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_3_write = 1'b1;
    end else begin
        d_o_3_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_4_blk_n = d_o_4_full_n;
    end else begin
        d_o_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_4_din = add_ln69_28_reg_1097;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_4_din = add_ln69_20_fu_359_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_4_din = add_ln69_12_fu_304_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_4_din = add_ln69_4_fu_236_p2;
    end else begin
        d_o_4_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_4_write = 1'b1;
    end else begin
        d_o_4_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_5_blk_n = d_o_5_full_n;
    end else begin
        d_o_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_5_din = add_ln69_29_reg_1107;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_5_din = add_ln69_21_fu_367_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_5_din = add_ln69_13_fu_309_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_5_din = add_ln69_5_fu_250_p2;
    end else begin
        d_o_5_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_5_write = 1'b1;
    end else begin
        d_o_5_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_6_blk_n = d_o_6_full_n;
    end else begin
        d_o_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_6_din = add_ln69_30_reg_1117;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_6_din = add_ln69_22_fu_375_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_6_din = add_ln69_14_fu_314_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_6_din = add_ln69_6_fu_264_p2;
    end else begin
        d_o_6_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_6_write = 1'b1;
    end else begin
        d_o_6_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        d_o_7_blk_n = d_o_7_full_n;
    end else begin
        d_o_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        d_o_7_din = add_ln69_31_reg_1127;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        d_o_7_din = add_ln69_23_fu_383_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        d_o_7_din = add_ln69_15_fu_319_p2;
    end else if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        d_o_7_din = add_ln69_7_fu_278_p2;
    end else begin
        d_o_7_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        d_o_7_write = 1'b1;
    end else begin
        d_o_7_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_10_fu_632_p2 = ($signed(sext_ln67_15_fu_629_p1) + $signed(sext_ln69_2_fu_546_p1));

assign add_ln67_12_fu_654_p2 = ($signed(acc_3) + $signed(sext_ln67_3_fu_525_p1));

assign add_ln67_13_fu_440_p2 = ($signed(sext_ln69_11_fu_348_p1) + $signed(sext_ln67_17_fu_436_p1));

assign add_ln67_14_fu_662_p2 = ($signed(sext_ln67_18_fu_659_p1) + $signed(sext_ln69_3_fu_549_p1));

assign add_ln67_16_fu_684_p2 = ($signed(acc_4) + $signed(sext_ln67_4_fu_528_p1));

assign add_ln67_17_fu_456_p2 = ($signed(sext_ln69_12_fu_356_p1) + $signed(sext_ln67_20_fu_452_p1));

assign add_ln67_18_fu_692_p2 = ($signed(sext_ln67_21_fu_689_p1) + $signed(sext_ln69_4_fu_552_p1));

assign add_ln67_1_fu_392_p2 = ($signed(sext_ln69_8_fu_324_p1) + $signed(sext_ln67_8_fu_388_p1));

assign add_ln67_20_fu_714_p2 = ($signed(acc_5) + $signed(sext_ln67_5_fu_531_p1));

assign add_ln67_21_fu_472_p2 = ($signed(sext_ln69_13_fu_364_p1) + $signed(sext_ln67_23_fu_468_p1));

assign add_ln67_22_fu_722_p2 = ($signed(sext_ln67_24_fu_719_p1) + $signed(sext_ln69_5_fu_555_p1));

assign add_ln67_24_fu_744_p2 = ($signed(acc_6) + $signed(sext_ln67_6_fu_534_p1));

assign add_ln67_25_fu_488_p2 = ($signed(sext_ln69_14_fu_372_p1) + $signed(sext_ln67_26_fu_484_p1));

assign add_ln67_26_fu_752_p2 = ($signed(sext_ln67_27_fu_749_p1) + $signed(sext_ln69_6_fu_558_p1));

assign add_ln67_28_fu_774_p2 = ($signed(acc_7) + $signed(sext_ln67_7_fu_537_p1));

assign add_ln67_29_fu_504_p2 = ($signed(sext_ln69_15_fu_380_p1) + $signed(sext_ln67_29_fu_500_p1));

assign add_ln67_2_fu_572_p2 = ($signed(sext_ln67_9_fu_569_p1) + $signed(sext_ln69_fu_540_p1));

assign add_ln67_30_fu_782_p2 = ($signed(sext_ln67_30_fu_779_p1) + $signed(sext_ln69_7_fu_561_p1));

assign add_ln67_4_fu_594_p2 = ($signed(acc_1) + $signed(sext_ln67_1_fu_519_p1));

assign add_ln67_5_fu_408_p2 = ($signed(sext_ln69_9_fu_332_p1) + $signed(sext_ln67_11_fu_404_p1));

assign add_ln67_6_fu_602_p2 = ($signed(sext_ln67_12_fu_599_p1) + $signed(sext_ln69_1_fu_543_p1));

assign add_ln67_8_fu_624_p2 = ($signed(acc_2) + $signed(sext_ln67_2_fu_522_p1));

assign add_ln67_9_fu_424_p2 = ($signed(sext_ln69_10_fu_340_p1) + $signed(sext_ln67_14_fu_420_p1));

assign add_ln67_fu_564_p2 = ($signed(acc_0) + $signed(sext_ln67_fu_516_p1));

assign add_ln69_10_fu_294_p2 = ($signed(d_i_2_read_1_reg_928) + $signed(add_ln69_2_reg_871));

assign add_ln69_11_fu_299_p2 = ($signed(d_i_3_read_1_reg_934) + $signed(add_ln69_3_reg_879));

assign add_ln69_12_fu_304_p2 = ($signed(d_i_4_read_1_reg_940) + $signed(add_ln69_4_reg_887));

assign add_ln69_13_fu_309_p2 = ($signed(d_i_5_read_1_reg_946) + $signed(add_ln69_5_reg_895));

assign add_ln69_14_fu_314_p2 = ($signed(d_i_6_read_1_reg_952) + $signed(add_ln69_6_reg_903));

assign add_ln69_15_fu_319_p2 = ($signed(d_i_7_read_1_reg_958) + $signed(add_ln69_7_reg_911));

assign add_ln69_16_fu_327_p2 = ($signed(d_i_0_read_2_reg_1004) + $signed(add_ln69_8_reg_964));

assign add_ln69_17_fu_335_p2 = ($signed(d_i_1_read_2_reg_1010) + $signed(add_ln69_9_reg_969));

assign add_ln69_18_fu_343_p2 = ($signed(d_i_2_read_2_reg_1016) + $signed(add_ln69_10_reg_974));

assign add_ln69_19_fu_351_p2 = ($signed(d_i_3_read_2_reg_1022) + $signed(add_ln69_11_reg_979));

assign add_ln69_1_fu_194_p2 = ($signed(d_i_1_read_reg_810) + $signed(trunc_ln67_1_fu_190_p1));

assign add_ln69_20_fu_359_p2 = ($signed(d_i_4_read_2_reg_1028) + $signed(add_ln69_12_reg_984));

assign add_ln69_21_fu_367_p2 = ($signed(d_i_5_read_2_reg_1034) + $signed(add_ln69_13_reg_989));

assign add_ln69_22_fu_375_p2 = ($signed(d_i_6_read_2_reg_1040) + $signed(add_ln69_14_reg_994));

assign add_ln69_23_fu_383_p2 = ($signed(d_i_7_read_2_reg_1046) + $signed(add_ln69_15_reg_999));

assign add_ln69_24_fu_398_p0 = d_i_0_dout;

assign add_ln69_24_fu_398_p2 = ($signed(add_ln69_24_fu_398_p0) + $signed(add_ln69_16_fu_327_p2));

assign add_ln69_25_fu_414_p0 = d_i_1_dout;

assign add_ln69_25_fu_414_p2 = ($signed(add_ln69_25_fu_414_p0) + $signed(add_ln69_17_fu_335_p2));

assign add_ln69_26_fu_430_p0 = d_i_2_dout;

assign add_ln69_26_fu_430_p2 = ($signed(add_ln69_26_fu_430_p0) + $signed(add_ln69_18_fu_343_p2));

assign add_ln69_27_fu_446_p0 = d_i_3_dout;

assign add_ln69_27_fu_446_p2 = ($signed(add_ln69_27_fu_446_p0) + $signed(add_ln69_19_fu_351_p2));

assign add_ln69_28_fu_462_p0 = d_i_4_dout;

assign add_ln69_28_fu_462_p2 = ($signed(add_ln69_28_fu_462_p0) + $signed(add_ln69_20_fu_359_p2));

assign add_ln69_29_fu_478_p0 = d_i_5_dout;

assign add_ln69_29_fu_478_p2 = ($signed(add_ln69_29_fu_478_p0) + $signed(add_ln69_21_fu_367_p2));

assign add_ln69_2_fu_208_p2 = ($signed(d_i_2_read_reg_816) + $signed(trunc_ln67_2_fu_204_p1));

assign add_ln69_30_fu_494_p0 = d_i_6_dout;

assign add_ln69_30_fu_494_p2 = ($signed(add_ln69_30_fu_494_p0) + $signed(add_ln69_22_fu_375_p2));

assign add_ln69_31_fu_510_p0 = d_i_7_dout;

assign add_ln69_31_fu_510_p2 = ($signed(add_ln69_31_fu_510_p0) + $signed(add_ln69_23_fu_383_p2));

assign add_ln69_3_fu_222_p2 = ($signed(d_i_3_read_reg_822) + $signed(trunc_ln67_3_fu_218_p1));

assign add_ln69_4_fu_236_p2 = ($signed(d_i_4_read_reg_828) + $signed(trunc_ln67_4_fu_232_p1));

assign add_ln69_5_fu_250_p2 = ($signed(d_i_5_read_reg_834) + $signed(trunc_ln67_5_fu_246_p1));

assign add_ln69_6_fu_264_p2 = ($signed(d_i_6_read_reg_840) + $signed(trunc_ln67_6_fu_260_p1));

assign add_ln69_7_fu_278_p2 = ($signed(d_i_7_read_reg_846) + $signed(trunc_ln67_7_fu_274_p1));

assign add_ln69_8_fu_284_p2 = ($signed(d_i_0_read_1_reg_916) + $signed(add_ln69_reg_855));

assign add_ln69_9_fu_289_p2 = ($signed(d_i_1_read_1_reg_922) + $signed(add_ln69_1_reg_863));

assign add_ln69_fu_180_p2 = ($signed(d_i_0_read_reg_804) + $signed(trunc_ln67_fu_176_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((d_i_7_empty_n == 1'b0) | (d_i_6_empty_n == 1'b0) | (d_i_5_empty_n == 1'b0) | (d_i_4_empty_n == 1'b0) | (d_i_3_empty_n == 1'b0) | (d_i_2_empty_n == 1'b0) | (d_i_1_empty_n == 1'b0) | (d_i_0_empty_n == 1'b0) | (d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((d_o_7_full_n == 1'b0) | (d_o_6_full_n == 1'b0) | (d_o_5_full_n == 1'b0) | (d_o_4_full_n == 1'b0) | (d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

assign sext_ln67_10_fu_578_p1 = $signed(add_ln67_2_fu_572_p2);

assign sext_ln67_11_fu_404_p0 = d_i_1_dout;

assign sext_ln67_11_fu_404_p1 = sext_ln67_11_fu_404_p0;

assign sext_ln67_12_fu_599_p1 = $signed(add_ln67_5_reg_1062);

assign sext_ln67_13_fu_608_p1 = $signed(add_ln67_6_fu_602_p2);

assign sext_ln67_14_fu_420_p0 = d_i_2_dout;

assign sext_ln67_14_fu_420_p1 = sext_ln67_14_fu_420_p0;

assign sext_ln67_15_fu_629_p1 = $signed(add_ln67_9_reg_1072);

assign sext_ln67_16_fu_638_p1 = $signed(add_ln67_10_fu_632_p2);

assign sext_ln67_17_fu_436_p0 = d_i_3_dout;

assign sext_ln67_17_fu_436_p1 = sext_ln67_17_fu_436_p0;

assign sext_ln67_18_fu_659_p1 = $signed(add_ln67_13_reg_1082);

assign sext_ln67_19_fu_668_p1 = $signed(add_ln67_14_fu_662_p2);

assign sext_ln67_1_fu_519_p1 = d_i_1_read_reg_810;

assign sext_ln67_20_fu_452_p0 = d_i_4_dout;

assign sext_ln67_20_fu_452_p1 = sext_ln67_20_fu_452_p0;

assign sext_ln67_21_fu_689_p1 = $signed(add_ln67_17_reg_1092);

assign sext_ln67_22_fu_698_p1 = $signed(add_ln67_18_fu_692_p2);

assign sext_ln67_23_fu_468_p0 = d_i_5_dout;

assign sext_ln67_23_fu_468_p1 = sext_ln67_23_fu_468_p0;

assign sext_ln67_24_fu_719_p1 = $signed(add_ln67_21_reg_1102);

assign sext_ln67_25_fu_728_p1 = $signed(add_ln67_22_fu_722_p2);

assign sext_ln67_26_fu_484_p0 = d_i_6_dout;

assign sext_ln67_26_fu_484_p1 = sext_ln67_26_fu_484_p0;

assign sext_ln67_27_fu_749_p1 = $signed(add_ln67_25_reg_1112);

assign sext_ln67_28_fu_758_p1 = $signed(add_ln67_26_fu_752_p2);

assign sext_ln67_29_fu_500_p0 = d_i_7_dout;

assign sext_ln67_29_fu_500_p1 = sext_ln67_29_fu_500_p0;

assign sext_ln67_2_fu_522_p1 = d_i_2_read_reg_816;

assign sext_ln67_30_fu_779_p1 = $signed(add_ln67_29_reg_1122);

assign sext_ln67_31_fu_788_p1 = $signed(add_ln67_30_fu_782_p2);

assign sext_ln67_3_fu_525_p1 = d_i_3_read_reg_822;

assign sext_ln67_4_fu_528_p1 = d_i_4_read_reg_828;

assign sext_ln67_5_fu_531_p1 = d_i_5_read_reg_834;

assign sext_ln67_6_fu_534_p1 = d_i_6_read_reg_840;

assign sext_ln67_7_fu_537_p1 = d_i_7_read_reg_846;

assign sext_ln67_8_fu_388_p0 = d_i_0_dout;

assign sext_ln67_8_fu_388_p1 = sext_ln67_8_fu_388_p0;

assign sext_ln67_9_fu_569_p1 = $signed(add_ln67_1_reg_1052);

assign sext_ln67_fu_516_p1 = d_i_0_read_reg_804;

assign sext_ln69_10_fu_340_p1 = d_i_2_read_2_reg_1016;

assign sext_ln69_11_fu_348_p1 = d_i_3_read_2_reg_1022;

assign sext_ln69_12_fu_356_p1 = d_i_4_read_2_reg_1028;

assign sext_ln69_13_fu_364_p1 = d_i_5_read_2_reg_1034;

assign sext_ln69_14_fu_372_p1 = d_i_6_read_2_reg_1040;

assign sext_ln69_15_fu_380_p1 = d_i_7_read_2_reg_1046;

assign sext_ln69_1_fu_543_p1 = d_i_1_read_1_reg_922;

assign sext_ln69_2_fu_546_p1 = d_i_2_read_1_reg_928;

assign sext_ln69_3_fu_549_p1 = d_i_3_read_1_reg_934;

assign sext_ln69_4_fu_552_p1 = d_i_4_read_1_reg_940;

assign sext_ln69_5_fu_555_p1 = d_i_5_read_1_reg_946;

assign sext_ln69_6_fu_558_p1 = d_i_6_read_1_reg_952;

assign sext_ln69_7_fu_561_p1 = d_i_7_read_1_reg_958;

assign sext_ln69_8_fu_324_p1 = d_i_0_read_2_reg_1004;

assign sext_ln69_9_fu_332_p1 = d_i_1_read_2_reg_1010;

assign sext_ln69_fu_540_p1 = d_i_0_read_1_reg_916;

assign temp_1_fu_612_p2 = ($signed(sext_ln67_13_fu_608_p1) + $signed(add_ln67_4_fu_594_p2));

assign temp_2_fu_642_p2 = ($signed(sext_ln67_16_fu_638_p1) + $signed(add_ln67_8_fu_624_p2));

assign temp_3_fu_672_p2 = ($signed(sext_ln67_19_fu_668_p1) + $signed(add_ln67_12_fu_654_p2));

assign temp_4_fu_702_p2 = ($signed(sext_ln67_22_fu_698_p1) + $signed(add_ln67_16_fu_684_p2));

assign temp_5_fu_732_p2 = ($signed(sext_ln67_25_fu_728_p1) + $signed(add_ln67_20_fu_714_p2));

assign temp_6_fu_762_p2 = ($signed(sext_ln67_28_fu_758_p1) + $signed(add_ln67_24_fu_744_p2));

assign temp_7_fu_792_p2 = ($signed(sext_ln67_31_fu_788_p1) + $signed(add_ln67_28_fu_774_p2));

assign temp_fu_582_p2 = ($signed(sext_ln67_10_fu_578_p1) + $signed(add_ln67_fu_564_p2));

assign trunc_ln67_1_fu_190_p1 = acc_1[15:0];

assign trunc_ln67_2_fu_204_p1 = acc_2[15:0];

assign trunc_ln67_3_fu_218_p1 = acc_3[15:0];

assign trunc_ln67_4_fu_232_p1 = acc_4[15:0];

assign trunc_ln67_5_fu_246_p1 = acc_5[15:0];

assign trunc_ln67_6_fu_260_p1 = acc_6[15:0];

assign trunc_ln67_7_fu_274_p1 = acc_7[15:0];

assign trunc_ln67_fu_176_p1 = acc_0[15:0];

endmodule //array_io
