// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Tool Version Limit: 2022.04
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_array_io (
volatile void* d_o_0,
volatile void* d_o_1,
volatile void* d_o_2,
volatile void* d_o_3,
volatile void* d_o_4,
volatile void* d_o_5,
volatile void* d_o_6,
volatile void* d_o_7,
volatile void* d_o_8,
volatile void* d_o_9,
volatile void* d_o_10,
volatile void* d_o_11,
volatile void* d_o_12,
volatile void* d_o_13,
volatile void* d_o_14,
volatile void* d_o_15,
volatile void* d_o_16,
volatile void* d_o_17,
volatile void* d_o_18,
volatile void* d_o_19,
volatile void* d_o_20,
volatile void* d_o_21,
volatile void* d_o_22,
volatile void* d_o_23,
volatile void* d_o_24,
volatile void* d_o_25,
volatile void* d_o_26,
volatile void* d_o_27,
volatile void* d_o_28,
volatile void* d_o_29,
volatile void* d_o_30,
volatile void* d_o_31,
volatile void* d_i_0,
volatile void* d_i_1,
volatile void* d_i_2,
volatile void* d_i_3,
volatile void* d_i_4,
volatile void* d_i_5,
volatile void* d_i_6,
volatile void* d_i_7,
volatile void* d_i_8,
volatile void* d_i_9,
volatile void* d_i_10,
volatile void* d_i_11,
volatile void* d_i_12,
volatile void* d_i_13,
volatile void* d_i_14,
volatile void* d_i_15,
volatile void* d_i_16,
volatile void* d_i_17,
volatile void* d_i_18,
volatile void* d_i_19,
volatile void* d_i_20,
volatile void* d_i_21,
volatile void* d_i_22,
volatile void* d_i_23,
volatile void* d_i_24,
volatile void* d_i_25,
volatile void* d_i_26,
volatile void* d_i_27,
volatile void* d_i_28,
volatile void* d_i_29,
volatile void* d_i_30,
volatile void* d_i_31);
