// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_io_array_io,hls_ip_2022_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.581000,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1306,HLS_SYN_LUT=2081,HLS_VERSION=2022_1}" *)

module array_io (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_o_0_din,
        d_o_0_full_n,
        d_o_0_write,
        d_o_1_din,
        d_o_1_full_n,
        d_o_1_write,
        d_i_address0,
        d_i_ce0,
        d_i_q0,
        d_i_address1,
        d_i_ce1,
        d_i_q1
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] d_o_0_din;
input   d_o_0_full_n;
output   d_o_0_write;
output  [15:0] d_o_1_din;
input   d_o_1_full_n;
output   d_o_1_write;
output  [4:0] d_i_address0;
output   d_i_ce0;
input  [15:0] d_i_q0;
output  [4:0] d_i_address1;
output   d_i_ce1;
input  [15:0] d_i_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] d_o_0_din;
reg d_o_0_write;
reg[15:0] d_o_1_din;
reg d_o_1_write;
reg[4:0] d_i_address0;
reg d_i_ce0;
reg[4:0] d_i_address1;
reg d_i_ce1;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] acc_0;
reg   [31:0] acc_1;
reg   [31:0] acc_2;
reg   [31:0] acc_3;
reg   [31:0] acc_4;
reg   [31:0] acc_5;
reg   [31:0] acc_6;
reg   [31:0] acc_7;
reg    d_o_0_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    d_o_1_blk_n;
reg  signed [15:0] d_i_load_reg_1051;
wire    ap_CS_fsm_state2;
reg  signed [15:0] d_i_load_1_reg_1057;
wire   [15:0] add_ln69_fu_425_p2;
reg   [15:0] add_ln69_reg_1076;
wire   [15:0] add_ln69_1_fu_439_p2;
reg   [15:0] add_ln69_1_reg_1084;
reg  signed [15:0] d_i_load_2_reg_1089;
reg  signed [15:0] d_i_load_3_reg_1095;
wire   [15:0] add_ln69_2_fu_453_p2;
reg   [15:0] add_ln69_2_reg_1114;
wire   [15:0] add_ln69_3_fu_467_p2;
reg   [15:0] add_ln69_3_reg_1122;
reg  signed [15:0] d_i_load_4_reg_1127;
reg  signed [15:0] d_i_load_5_reg_1133;
wire   [15:0] add_ln69_4_fu_481_p2;
reg   [15:0] add_ln69_4_reg_1152;
wire   [15:0] add_ln69_5_fu_495_p2;
reg   [15:0] add_ln69_5_reg_1160;
reg  signed [15:0] d_i_load_6_reg_1165;
reg  signed [15:0] d_i_load_7_reg_1171;
wire   [15:0] add_ln69_6_fu_509_p2;
reg   [15:0] add_ln69_6_reg_1190;
wire   [15:0] add_ln69_7_fu_523_p2;
reg   [15:0] add_ln69_7_reg_1198;
reg  signed [15:0] d_i_load_8_reg_1203;
reg  signed [15:0] d_i_load_9_reg_1209;
wire   [15:0] add_ln69_8_fu_529_p2;
reg   [15:0] add_ln69_8_reg_1225;
wire   [15:0] add_ln69_9_fu_534_p2;
reg   [15:0] add_ln69_9_reg_1230;
reg  signed [15:0] d_i_load_10_reg_1235;
reg  signed [15:0] d_i_load_11_reg_1241;
wire   [15:0] add_ln69_10_fu_539_p2;
reg   [15:0] add_ln69_10_reg_1257;
wire   [15:0] add_ln69_11_fu_544_p2;
reg   [15:0] add_ln69_11_reg_1262;
reg  signed [15:0] d_i_load_12_reg_1267;
reg  signed [15:0] d_i_load_13_reg_1273;
wire   [15:0] add_ln69_12_fu_549_p2;
reg   [15:0] add_ln69_12_reg_1289;
wire   [15:0] add_ln69_13_fu_554_p2;
reg   [15:0] add_ln69_13_reg_1294;
reg  signed [15:0] d_i_load_14_reg_1299;
reg  signed [15:0] d_i_load_15_reg_1305;
wire   [15:0] add_ln69_14_fu_559_p2;
reg   [15:0] add_ln69_14_reg_1321;
wire   [15:0] add_ln69_15_fu_564_p2;
reg   [15:0] add_ln69_15_reg_1326;
reg  signed [15:0] d_i_load_16_reg_1331;
reg  signed [15:0] d_i_load_17_reg_1337;
wire   [15:0] add_ln69_16_fu_569_p2;
reg   [15:0] add_ln69_16_reg_1353;
wire   [15:0] add_ln69_17_fu_574_p2;
reg   [15:0] add_ln69_17_reg_1358;
reg  signed [15:0] d_i_load_18_reg_1363;
reg  signed [15:0] d_i_load_19_reg_1369;
wire   [15:0] add_ln69_18_fu_579_p2;
reg   [15:0] add_ln69_18_reg_1385;
wire   [15:0] add_ln69_19_fu_584_p2;
reg   [15:0] add_ln69_19_reg_1390;
reg  signed [15:0] d_i_load_20_reg_1395;
reg  signed [15:0] d_i_load_21_reg_1401;
wire   [15:0] add_ln69_20_fu_589_p2;
reg   [15:0] add_ln69_20_reg_1417;
wire   [15:0] add_ln69_21_fu_594_p2;
reg   [15:0] add_ln69_21_reg_1422;
reg  signed [15:0] d_i_load_22_reg_1427;
reg  signed [15:0] d_i_load_23_reg_1433;
wire   [15:0] add_ln69_22_fu_605_p2;
reg   [15:0] add_ln69_22_reg_1449;
wire   [15:0] add_ln69_23_fu_610_p2;
reg   [15:0] add_ln69_23_reg_1454;
wire   [16:0] add_ln67_1_fu_619_p2;
reg   [16:0] add_ln67_1_reg_1459;
wire   [15:0] add_ln69_24_fu_625_p2;
reg   [15:0] add_ln69_24_reg_1464;
wire   [16:0] add_ln67_5_fu_634_p2;
reg   [16:0] add_ln67_5_reg_1469;
wire   [15:0] add_ln69_25_fu_640_p2;
reg   [15:0] add_ln69_25_reg_1474;
wire   [16:0] add_ln67_9_fu_727_p2;
reg   [16:0] add_ln67_9_reg_1489;
wire   [15:0] add_ln69_26_fu_733_p2;
reg   [15:0] add_ln69_26_reg_1494;
wire   [16:0] add_ln67_13_fu_742_p2;
reg   [16:0] add_ln67_13_reg_1499;
wire   [15:0] add_ln69_27_fu_748_p2;
reg   [15:0] add_ln69_27_reg_1504;
wire   [16:0] add_ln67_17_fu_835_p2;
reg   [16:0] add_ln67_17_reg_1519;
wire   [15:0] add_ln69_28_fu_841_p2;
reg   [15:0] add_ln69_28_reg_1524;
wire   [16:0] add_ln67_21_fu_850_p2;
reg   [16:0] add_ln67_21_reg_1529;
wire   [15:0] add_ln69_29_fu_856_p2;
reg   [15:0] add_ln69_29_reg_1534;
wire   [16:0] add_ln67_25_fu_943_p2;
reg   [16:0] add_ln67_25_reg_1549;
wire   [15:0] add_ln69_30_fu_949_p2;
reg   [15:0] add_ln69_30_reg_1554;
wire   [16:0] add_ln67_29_fu_958_p2;
reg   [16:0] add_ln67_29_reg_1559;
wire   [15:0] add_ln69_31_fu_964_p2;
reg   [15:0] add_ln69_31_reg_1564;
wire   [31:0] temp_fu_681_p2;
reg    ap_block_state15;
wire   [31:0] temp_1_fu_711_p2;
wire   [31:0] temp_2_fu_789_p2;
reg    ap_block_state16;
wire   [31:0] temp_3_fu_819_p2;
wire   [31:0] temp_4_fu_897_p2;
reg    ap_block_state17;
wire   [31:0] temp_5_fu_927_p2;
wire   [31:0] temp_6_fu_999_p2;
reg    ap_block_state18;
wire   [31:0] temp_7_fu_1029_p2;
reg    ap_block_state3;
reg    ap_block_state4;
reg    ap_block_state5;
reg    ap_block_state6;
reg    ap_block_state7;
reg    ap_block_state8;
reg    ap_block_state9;
reg    ap_block_state10;
reg    ap_block_state11;
reg    ap_block_state12;
reg    ap_block_state13;
reg    ap_block_state14;
wire   [15:0] trunc_ln67_fu_421_p1;
wire   [15:0] trunc_ln67_1_fu_435_p1;
wire   [15:0] trunc_ln67_2_fu_449_p1;
wire   [15:0] trunc_ln67_3_fu_463_p1;
wire   [15:0] trunc_ln67_4_fu_477_p1;
wire   [15:0] trunc_ln67_5_fu_491_p1;
wire   [15:0] trunc_ln67_6_fu_505_p1;
wire   [15:0] trunc_ln67_7_fu_519_p1;
wire  signed [15:0] sext_ln67_8_fu_615_p0;
wire  signed [16:0] sext_ln69_8_fu_599_p1;
wire  signed [16:0] sext_ln67_8_fu_615_p1;
wire  signed [15:0] add_ln69_24_fu_625_p0;
wire  signed [15:0] sext_ln67_11_fu_630_p0;
wire  signed [16:0] sext_ln69_9_fu_602_p1;
wire  signed [16:0] sext_ln67_11_fu_630_p1;
wire  signed [15:0] add_ln69_25_fu_640_p0;
wire  signed [31:0] sext_ln67_fu_645_p1;
wire  signed [17:0] sext_ln67_9_fu_668_p1;
wire  signed [17:0] sext_ln69_fu_651_p1;
wire   [17:0] add_ln67_2_fu_671_p2;
wire  signed [31:0] sext_ln67_10_fu_677_p1;
wire   [31:0] add_ln67_fu_663_p2;
wire  signed [31:0] sext_ln67_1_fu_648_p1;
wire  signed [17:0] sext_ln67_12_fu_698_p1;
wire  signed [17:0] sext_ln69_1_fu_654_p1;
wire   [17:0] add_ln67_6_fu_701_p2;
wire  signed [31:0] sext_ln67_13_fu_707_p1;
wire   [31:0] add_ln67_4_fu_693_p2;
wire  signed [15:0] sext_ln67_14_fu_723_p0;
wire  signed [16:0] sext_ln69_10_fu_657_p1;
wire  signed [16:0] sext_ln67_14_fu_723_p1;
wire  signed [15:0] add_ln69_26_fu_733_p0;
wire  signed [15:0] sext_ln67_17_fu_738_p0;
wire  signed [16:0] sext_ln69_11_fu_660_p1;
wire  signed [16:0] sext_ln67_17_fu_738_p1;
wire  signed [15:0] add_ln69_27_fu_748_p0;
wire  signed [31:0] sext_ln67_2_fu_753_p1;
wire  signed [17:0] sext_ln67_15_fu_776_p1;
wire  signed [17:0] sext_ln69_2_fu_759_p1;
wire   [17:0] add_ln67_10_fu_779_p2;
wire  signed [31:0] sext_ln67_16_fu_785_p1;
wire   [31:0] add_ln67_8_fu_771_p2;
wire  signed [31:0] sext_ln67_3_fu_756_p1;
wire  signed [17:0] sext_ln67_18_fu_806_p1;
wire  signed [17:0] sext_ln69_3_fu_762_p1;
wire   [17:0] add_ln67_14_fu_809_p2;
wire  signed [31:0] sext_ln67_19_fu_815_p1;
wire   [31:0] add_ln67_12_fu_801_p2;
wire  signed [15:0] sext_ln67_20_fu_831_p0;
wire  signed [16:0] sext_ln69_12_fu_765_p1;
wire  signed [16:0] sext_ln67_20_fu_831_p1;
wire  signed [15:0] add_ln69_28_fu_841_p0;
wire  signed [15:0] sext_ln67_23_fu_846_p0;
wire  signed [16:0] sext_ln69_13_fu_768_p1;
wire  signed [16:0] sext_ln67_23_fu_846_p1;
wire  signed [15:0] add_ln69_29_fu_856_p0;
wire  signed [31:0] sext_ln67_4_fu_861_p1;
wire  signed [17:0] sext_ln67_21_fu_884_p1;
wire  signed [17:0] sext_ln69_4_fu_867_p1;
wire   [17:0] add_ln67_18_fu_887_p2;
wire  signed [31:0] sext_ln67_22_fu_893_p1;
wire   [31:0] add_ln67_16_fu_879_p2;
wire  signed [31:0] sext_ln67_5_fu_864_p1;
wire  signed [17:0] sext_ln67_24_fu_914_p1;
wire  signed [17:0] sext_ln69_5_fu_870_p1;
wire   [17:0] add_ln67_22_fu_917_p2;
wire  signed [31:0] sext_ln67_25_fu_923_p1;
wire   [31:0] add_ln67_20_fu_909_p2;
wire  signed [15:0] sext_ln67_26_fu_939_p0;
wire  signed [16:0] sext_ln69_14_fu_873_p1;
wire  signed [16:0] sext_ln67_26_fu_939_p1;
wire  signed [15:0] add_ln69_30_fu_949_p0;
wire  signed [15:0] sext_ln67_29_fu_954_p0;
wire  signed [16:0] sext_ln69_15_fu_876_p1;
wire  signed [16:0] sext_ln67_29_fu_954_p1;
wire  signed [15:0] add_ln69_31_fu_964_p0;
wire  signed [31:0] sext_ln67_6_fu_969_p1;
wire  signed [17:0] sext_ln67_27_fu_986_p1;
wire  signed [17:0] sext_ln69_6_fu_975_p1;
wire   [17:0] add_ln67_26_fu_989_p2;
wire  signed [31:0] sext_ln67_28_fu_995_p1;
wire   [31:0] add_ln67_24_fu_981_p2;
wire  signed [31:0] sext_ln67_7_fu_972_p1;
wire  signed [17:0] sext_ln67_30_fu_1016_p1;
wire  signed [17:0] sext_ln69_7_fu_978_p1;
wire   [17:0] add_ln67_30_fu_1019_p2;
wire  signed [31:0] sext_ln67_31_fu_1025_p1;
wire   [31:0] add_ln67_28_fu_1011_p2;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 acc_0 = 32'd0;
#0 acc_1 = 32'd0;
#0 acc_2 = 32'd0;
#0 acc_3 = 32'd0;
#0 acc_4 = 32'd0;
#0 acc_5 = 32'd0;
#0 acc_6 = 32'd0;
#0 acc_7 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
        acc_0 <= temp_fu_681_p2;
        acc_1 <= temp_1_fu_711_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16))) begin
        acc_2 <= temp_2_fu_789_p2;
        acc_3 <= temp_3_fu_819_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        acc_4 <= temp_4_fu_897_p2;
        acc_5 <= temp_5_fu_927_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        acc_6 <= temp_6_fu_999_p2;
        acc_7 <= temp_7_fu_1029_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln67_13_reg_1499 <= add_ln67_13_fu_742_p2;
        add_ln67_9_reg_1489 <= add_ln67_9_fu_727_p2;
        add_ln69_26_reg_1494 <= add_ln69_26_fu_733_p2;
        add_ln69_27_reg_1504 <= add_ln69_27_fu_748_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        add_ln67_17_reg_1519 <= add_ln67_17_fu_835_p2;
        add_ln67_21_reg_1529 <= add_ln67_21_fu_850_p2;
        add_ln69_28_reg_1524 <= add_ln69_28_fu_841_p2;
        add_ln69_29_reg_1534 <= add_ln69_29_fu_856_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln67_1_reg_1459 <= add_ln67_1_fu_619_p2;
        add_ln67_5_reg_1469 <= add_ln67_5_fu_634_p2;
        add_ln69_22_reg_1449 <= add_ln69_22_fu_605_p2;
        add_ln69_23_reg_1454 <= add_ln69_23_fu_610_p2;
        add_ln69_24_reg_1464 <= add_ln69_24_fu_625_p2;
        add_ln69_25_reg_1474 <= add_ln69_25_fu_640_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln67_25_reg_1549 <= add_ln67_25_fu_943_p2;
        add_ln67_29_reg_1559 <= add_ln67_29_fu_958_p2;
        add_ln69_30_reg_1554 <= add_ln69_30_fu_949_p2;
        add_ln69_31_reg_1564 <= add_ln69_31_fu_964_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln69_10_reg_1257 <= add_ln69_10_fu_539_p2;
        add_ln69_11_reg_1262 <= add_ln69_11_fu_544_p2;
        d_i_load_12_reg_1267 <= d_i_q1;
        d_i_load_13_reg_1273 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln69_12_reg_1289 <= add_ln69_12_fu_549_p2;
        add_ln69_13_reg_1294 <= add_ln69_13_fu_554_p2;
        d_i_load_14_reg_1299 <= d_i_q1;
        d_i_load_15_reg_1305 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln69_14_reg_1321 <= add_ln69_14_fu_559_p2;
        add_ln69_15_reg_1326 <= add_ln69_15_fu_564_p2;
        d_i_load_16_reg_1331 <= d_i_q1;
        d_i_load_17_reg_1337 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln69_16_reg_1353 <= add_ln69_16_fu_569_p2;
        add_ln69_17_reg_1358 <= add_ln69_17_fu_574_p2;
        d_i_load_18_reg_1363 <= d_i_q1;
        d_i_load_19_reg_1369 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln69_18_reg_1385 <= add_ln69_18_fu_579_p2;
        add_ln69_19_reg_1390 <= add_ln69_19_fu_584_p2;
        d_i_load_20_reg_1395 <= d_i_q1;
        d_i_load_21_reg_1401 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln69_1_reg_1084 <= add_ln69_1_fu_439_p2;
        add_ln69_reg_1076 <= add_ln69_fu_425_p2;
        d_i_load_2_reg_1089 <= d_i_q1;
        d_i_load_3_reg_1095 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln69_20_reg_1417 <= add_ln69_20_fu_589_p2;
        add_ln69_21_reg_1422 <= add_ln69_21_fu_594_p2;
        d_i_load_22_reg_1427 <= d_i_q1;
        d_i_load_23_reg_1433 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln69_2_reg_1114 <= add_ln69_2_fu_453_p2;
        add_ln69_3_reg_1122 <= add_ln69_3_fu_467_p2;
        d_i_load_4_reg_1127 <= d_i_q1;
        d_i_load_5_reg_1133 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln69_4_reg_1152 <= add_ln69_4_fu_481_p2;
        add_ln69_5_reg_1160 <= add_ln69_5_fu_495_p2;
        d_i_load_6_reg_1165 <= d_i_q1;
        d_i_load_7_reg_1171 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln69_6_reg_1190 <= add_ln69_6_fu_509_p2;
        add_ln69_7_reg_1198 <= add_ln69_7_fu_523_p2;
        d_i_load_8_reg_1203 <= d_i_q1;
        d_i_load_9_reg_1209 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln69_8_reg_1225 <= add_ln69_8_fu_529_p2;
        add_ln69_9_reg_1230 <= add_ln69_9_fu_534_p2;
        d_i_load_10_reg_1235 <= d_i_q1;
        d_i_load_11_reg_1241 <= d_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_load_1_reg_1057 <= d_i_q0;
        d_i_load_reg_1051 <= d_i_q1;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        d_i_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_i_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_i_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_i_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_i_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_i_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_i_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_i_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_address0 = 64'd1;
    end else begin
        d_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        d_i_address1 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_i_address1 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_i_address1 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_i_address1 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_i_address1 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_i_address1 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_i_address1 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_i_address1 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_address1 = 64'd0;
    end else begin
        d_i_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)))) begin
        d_i_ce0 = 1'b1;
    end else begin
        d_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)))) begin
        d_i_ce1 = 1'b1;
    end else begin
        d_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        d_o_0_blk_n = d_o_0_full_n;
    end else begin
        d_o_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            d_o_0_din = add_ln69_30_reg_1554;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            d_o_0_din = add_ln69_28_reg_1524;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            d_o_0_din = add_ln69_26_reg_1494;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            d_o_0_din = add_ln69_24_reg_1464;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            d_o_0_din = add_ln69_22_fu_605_p2;
        end else if ((1'b1 == ap_CS_fsm_state13)) begin
            d_o_0_din = add_ln69_20_fu_589_p2;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            d_o_0_din = add_ln69_18_fu_579_p2;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_0_din = add_ln69_16_fu_569_p2;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_0_din = add_ln69_14_fu_559_p2;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_0_din = add_ln69_12_fu_549_p2;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_0_din = add_ln69_10_fu_539_p2;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_0_din = add_ln69_8_fu_529_p2;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_0_din = add_ln69_6_fu_509_p2;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_0_din = add_ln69_4_fu_481_p2;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_0_din = add_ln69_2_fu_453_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            d_o_0_din = add_ln69_fu_425_p2;
        end else begin
            d_o_0_din = 'bx;
        end
    end else begin
        d_o_0_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)))) begin
        d_o_0_write = 1'b1;
    end else begin
        d_o_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        d_o_1_blk_n = d_o_1_full_n;
    end else begin
        d_o_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            d_o_1_din = add_ln69_31_reg_1564;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            d_o_1_din = add_ln69_29_reg_1534;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            d_o_1_din = add_ln69_27_reg_1504;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            d_o_1_din = add_ln69_25_reg_1474;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            d_o_1_din = add_ln69_23_fu_610_p2;
        end else if ((1'b1 == ap_CS_fsm_state13)) begin
            d_o_1_din = add_ln69_21_fu_594_p2;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            d_o_1_din = add_ln69_19_fu_584_p2;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_1_din = add_ln69_17_fu_574_p2;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_1_din = add_ln69_15_fu_564_p2;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_1_din = add_ln69_13_fu_554_p2;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_1_din = add_ln69_11_fu_544_p2;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_1_din = add_ln69_9_fu_534_p2;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_1_din = add_ln69_7_fu_523_p2;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_1_din = add_ln69_5_fu_495_p2;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_1_din = add_ln69_3_fu_467_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            d_o_1_din = add_ln69_1_fu_439_p2;
        end else begin
            d_o_1_din = 'bx;
        end
    end else begin
        d_o_1_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)))) begin
        d_o_1_write = 1'b1;
    end else begin
        d_o_1_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_10_fu_779_p2 = ($signed(sext_ln67_15_fu_776_p1) + $signed(sext_ln69_2_fu_759_p1));

assign add_ln67_12_fu_801_p2 = ($signed(acc_3) + $signed(sext_ln67_3_fu_756_p1));

assign add_ln67_13_fu_742_p2 = ($signed(sext_ln69_11_fu_660_p1) + $signed(sext_ln67_17_fu_738_p1));

assign add_ln67_14_fu_809_p2 = ($signed(sext_ln67_18_fu_806_p1) + $signed(sext_ln69_3_fu_762_p1));

assign add_ln67_16_fu_879_p2 = ($signed(acc_4) + $signed(sext_ln67_4_fu_861_p1));

assign add_ln67_17_fu_835_p2 = ($signed(sext_ln69_12_fu_765_p1) + $signed(sext_ln67_20_fu_831_p1));

assign add_ln67_18_fu_887_p2 = ($signed(sext_ln67_21_fu_884_p1) + $signed(sext_ln69_4_fu_867_p1));

assign add_ln67_1_fu_619_p2 = ($signed(sext_ln69_8_fu_599_p1) + $signed(sext_ln67_8_fu_615_p1));

assign add_ln67_20_fu_909_p2 = ($signed(acc_5) + $signed(sext_ln67_5_fu_864_p1));

assign add_ln67_21_fu_850_p2 = ($signed(sext_ln69_13_fu_768_p1) + $signed(sext_ln67_23_fu_846_p1));

assign add_ln67_22_fu_917_p2 = ($signed(sext_ln67_24_fu_914_p1) + $signed(sext_ln69_5_fu_870_p1));

assign add_ln67_24_fu_981_p2 = ($signed(acc_6) + $signed(sext_ln67_6_fu_969_p1));

assign add_ln67_25_fu_943_p2 = ($signed(sext_ln69_14_fu_873_p1) + $signed(sext_ln67_26_fu_939_p1));

assign add_ln67_26_fu_989_p2 = ($signed(sext_ln67_27_fu_986_p1) + $signed(sext_ln69_6_fu_975_p1));

assign add_ln67_28_fu_1011_p2 = ($signed(acc_7) + $signed(sext_ln67_7_fu_972_p1));

assign add_ln67_29_fu_958_p2 = ($signed(sext_ln69_15_fu_876_p1) + $signed(sext_ln67_29_fu_954_p1));

assign add_ln67_2_fu_671_p2 = ($signed(sext_ln67_9_fu_668_p1) + $signed(sext_ln69_fu_651_p1));

assign add_ln67_30_fu_1019_p2 = ($signed(sext_ln67_30_fu_1016_p1) + $signed(sext_ln69_7_fu_978_p1));

assign add_ln67_4_fu_693_p2 = ($signed(acc_1) + $signed(sext_ln67_1_fu_648_p1));

assign add_ln67_5_fu_634_p2 = ($signed(sext_ln69_9_fu_602_p1) + $signed(sext_ln67_11_fu_630_p1));

assign add_ln67_6_fu_701_p2 = ($signed(sext_ln67_12_fu_698_p1) + $signed(sext_ln69_1_fu_654_p1));

assign add_ln67_8_fu_771_p2 = ($signed(acc_2) + $signed(sext_ln67_2_fu_753_p1));

assign add_ln67_9_fu_727_p2 = ($signed(sext_ln69_10_fu_657_p1) + $signed(sext_ln67_14_fu_723_p1));

assign add_ln67_fu_663_p2 = ($signed(acc_0) + $signed(sext_ln67_fu_645_p1));

assign add_ln69_10_fu_539_p2 = ($signed(d_i_load_10_reg_1235) + $signed(add_ln69_2_reg_1114));

assign add_ln69_11_fu_544_p2 = ($signed(d_i_load_11_reg_1241) + $signed(add_ln69_3_reg_1122));

assign add_ln69_12_fu_549_p2 = ($signed(d_i_load_12_reg_1267) + $signed(add_ln69_4_reg_1152));

assign add_ln69_13_fu_554_p2 = ($signed(d_i_load_13_reg_1273) + $signed(add_ln69_5_reg_1160));

assign add_ln69_14_fu_559_p2 = ($signed(d_i_load_14_reg_1299) + $signed(add_ln69_6_reg_1190));

assign add_ln69_15_fu_564_p2 = ($signed(d_i_load_15_reg_1305) + $signed(add_ln69_7_reg_1198));

assign add_ln69_16_fu_569_p2 = ($signed(d_i_load_16_reg_1331) + $signed(add_ln69_8_reg_1225));

assign add_ln69_17_fu_574_p2 = ($signed(d_i_load_17_reg_1337) + $signed(add_ln69_9_reg_1230));

assign add_ln69_18_fu_579_p2 = ($signed(d_i_load_18_reg_1363) + $signed(add_ln69_10_reg_1257));

assign add_ln69_19_fu_584_p2 = ($signed(d_i_load_19_reg_1369) + $signed(add_ln69_11_reg_1262));

assign add_ln69_1_fu_439_p2 = ($signed(d_i_load_1_reg_1057) + $signed(trunc_ln67_1_fu_435_p1));

assign add_ln69_20_fu_589_p2 = ($signed(d_i_load_20_reg_1395) + $signed(add_ln69_12_reg_1289));

assign add_ln69_21_fu_594_p2 = ($signed(d_i_load_21_reg_1401) + $signed(add_ln69_13_reg_1294));

assign add_ln69_22_fu_605_p2 = ($signed(d_i_load_22_reg_1427) + $signed(add_ln69_14_reg_1321));

assign add_ln69_23_fu_610_p2 = ($signed(d_i_load_23_reg_1433) + $signed(add_ln69_15_reg_1326));

assign add_ln69_24_fu_625_p0 = d_i_q1;

assign add_ln69_24_fu_625_p2 = ($signed(add_ln69_24_fu_625_p0) + $signed(add_ln69_16_reg_1353));

assign add_ln69_25_fu_640_p0 = d_i_q0;

assign add_ln69_25_fu_640_p2 = ($signed(add_ln69_25_fu_640_p0) + $signed(add_ln69_17_reg_1358));

assign add_ln69_26_fu_733_p0 = d_i_q1;

assign add_ln69_26_fu_733_p2 = ($signed(add_ln69_26_fu_733_p0) + $signed(add_ln69_18_reg_1385));

assign add_ln69_27_fu_748_p0 = d_i_q0;

assign add_ln69_27_fu_748_p2 = ($signed(add_ln69_27_fu_748_p0) + $signed(add_ln69_19_reg_1390));

assign add_ln69_28_fu_841_p0 = d_i_q1;

assign add_ln69_28_fu_841_p2 = ($signed(add_ln69_28_fu_841_p0) + $signed(add_ln69_20_reg_1417));

assign add_ln69_29_fu_856_p0 = d_i_q0;

assign add_ln69_29_fu_856_p2 = ($signed(add_ln69_29_fu_856_p0) + $signed(add_ln69_21_reg_1422));

assign add_ln69_2_fu_453_p2 = ($signed(d_i_load_2_reg_1089) + $signed(trunc_ln67_2_fu_449_p1));

assign add_ln69_30_fu_949_p0 = d_i_q1;

assign add_ln69_30_fu_949_p2 = ($signed(add_ln69_30_fu_949_p0) + $signed(add_ln69_22_reg_1449));

assign add_ln69_31_fu_964_p0 = d_i_q0;

assign add_ln69_31_fu_964_p2 = ($signed(add_ln69_31_fu_964_p0) + $signed(add_ln69_23_reg_1454));

assign add_ln69_3_fu_467_p2 = ($signed(d_i_load_3_reg_1095) + $signed(trunc_ln67_3_fu_463_p1));

assign add_ln69_4_fu_481_p2 = ($signed(d_i_load_4_reg_1127) + $signed(trunc_ln67_4_fu_477_p1));

assign add_ln69_5_fu_495_p2 = ($signed(d_i_load_5_reg_1133) + $signed(trunc_ln67_5_fu_491_p1));

assign add_ln69_6_fu_509_p2 = ($signed(d_i_load_6_reg_1165) + $signed(trunc_ln67_6_fu_505_p1));

assign add_ln69_7_fu_523_p2 = ($signed(d_i_load_7_reg_1171) + $signed(trunc_ln67_7_fu_519_p1));

assign add_ln69_8_fu_529_p2 = ($signed(d_i_load_8_reg_1203) + $signed(add_ln69_reg_1076));

assign add_ln69_9_fu_534_p2 = ($signed(d_i_load_9_reg_1209) + $signed(add_ln69_1_reg_1084));

assign add_ln69_fu_425_p2 = ($signed(d_i_load_reg_1051) + $signed(trunc_ln67_fu_421_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state11 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state12 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state13 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state14 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state15 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state16 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state17 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state18 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state8 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state9 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

assign sext_ln67_10_fu_677_p1 = $signed(add_ln67_2_fu_671_p2);

assign sext_ln67_11_fu_630_p0 = d_i_q0;

assign sext_ln67_11_fu_630_p1 = sext_ln67_11_fu_630_p0;

assign sext_ln67_12_fu_698_p1 = $signed(add_ln67_5_reg_1469);

assign sext_ln67_13_fu_707_p1 = $signed(add_ln67_6_fu_701_p2);

assign sext_ln67_14_fu_723_p0 = d_i_q1;

assign sext_ln67_14_fu_723_p1 = sext_ln67_14_fu_723_p0;

assign sext_ln67_15_fu_776_p1 = $signed(add_ln67_9_reg_1489);

assign sext_ln67_16_fu_785_p1 = $signed(add_ln67_10_fu_779_p2);

assign sext_ln67_17_fu_738_p0 = d_i_q0;

assign sext_ln67_17_fu_738_p1 = sext_ln67_17_fu_738_p0;

assign sext_ln67_18_fu_806_p1 = $signed(add_ln67_13_reg_1499);

assign sext_ln67_19_fu_815_p1 = $signed(add_ln67_14_fu_809_p2);

assign sext_ln67_1_fu_648_p1 = d_i_load_1_reg_1057;

assign sext_ln67_20_fu_831_p0 = d_i_q1;

assign sext_ln67_20_fu_831_p1 = sext_ln67_20_fu_831_p0;

assign sext_ln67_21_fu_884_p1 = $signed(add_ln67_17_reg_1519);

assign sext_ln67_22_fu_893_p1 = $signed(add_ln67_18_fu_887_p2);

assign sext_ln67_23_fu_846_p0 = d_i_q0;

assign sext_ln67_23_fu_846_p1 = sext_ln67_23_fu_846_p0;

assign sext_ln67_24_fu_914_p1 = $signed(add_ln67_21_reg_1529);

assign sext_ln67_25_fu_923_p1 = $signed(add_ln67_22_fu_917_p2);

assign sext_ln67_26_fu_939_p0 = d_i_q1;

assign sext_ln67_26_fu_939_p1 = sext_ln67_26_fu_939_p0;

assign sext_ln67_27_fu_986_p1 = $signed(add_ln67_25_reg_1549);

assign sext_ln67_28_fu_995_p1 = $signed(add_ln67_26_fu_989_p2);

assign sext_ln67_29_fu_954_p0 = d_i_q0;

assign sext_ln67_29_fu_954_p1 = sext_ln67_29_fu_954_p0;

assign sext_ln67_2_fu_753_p1 = d_i_load_2_reg_1089;

assign sext_ln67_30_fu_1016_p1 = $signed(add_ln67_29_reg_1559);

assign sext_ln67_31_fu_1025_p1 = $signed(add_ln67_30_fu_1019_p2);

assign sext_ln67_3_fu_756_p1 = d_i_load_3_reg_1095;

assign sext_ln67_4_fu_861_p1 = d_i_load_4_reg_1127;

assign sext_ln67_5_fu_864_p1 = d_i_load_5_reg_1133;

assign sext_ln67_6_fu_969_p1 = d_i_load_6_reg_1165;

assign sext_ln67_7_fu_972_p1 = d_i_load_7_reg_1171;

assign sext_ln67_8_fu_615_p0 = d_i_q1;

assign sext_ln67_8_fu_615_p1 = sext_ln67_8_fu_615_p0;

assign sext_ln67_9_fu_668_p1 = $signed(add_ln67_1_reg_1459);

assign sext_ln67_fu_645_p1 = d_i_load_reg_1051;

assign sext_ln69_10_fu_657_p1 = d_i_load_18_reg_1363;

assign sext_ln69_11_fu_660_p1 = d_i_load_19_reg_1369;

assign sext_ln69_12_fu_765_p1 = d_i_load_20_reg_1395;

assign sext_ln69_13_fu_768_p1 = d_i_load_21_reg_1401;

assign sext_ln69_14_fu_873_p1 = d_i_load_22_reg_1427;

assign sext_ln69_15_fu_876_p1 = d_i_load_23_reg_1433;

assign sext_ln69_1_fu_654_p1 = d_i_load_9_reg_1209;

assign sext_ln69_2_fu_759_p1 = d_i_load_10_reg_1235;

assign sext_ln69_3_fu_762_p1 = d_i_load_11_reg_1241;

assign sext_ln69_4_fu_867_p1 = d_i_load_12_reg_1267;

assign sext_ln69_5_fu_870_p1 = d_i_load_13_reg_1273;

assign sext_ln69_6_fu_975_p1 = d_i_load_14_reg_1299;

assign sext_ln69_7_fu_978_p1 = d_i_load_15_reg_1305;

assign sext_ln69_8_fu_599_p1 = d_i_load_16_reg_1331;

assign sext_ln69_9_fu_602_p1 = d_i_load_17_reg_1337;

assign sext_ln69_fu_651_p1 = d_i_load_8_reg_1203;

assign temp_1_fu_711_p2 = ($signed(sext_ln67_13_fu_707_p1) + $signed(add_ln67_4_fu_693_p2));

assign temp_2_fu_789_p2 = ($signed(sext_ln67_16_fu_785_p1) + $signed(add_ln67_8_fu_771_p2));

assign temp_3_fu_819_p2 = ($signed(sext_ln67_19_fu_815_p1) + $signed(add_ln67_12_fu_801_p2));

assign temp_4_fu_897_p2 = ($signed(sext_ln67_22_fu_893_p1) + $signed(add_ln67_16_fu_879_p2));

assign temp_5_fu_927_p2 = ($signed(sext_ln67_25_fu_923_p1) + $signed(add_ln67_20_fu_909_p2));

assign temp_6_fu_999_p2 = ($signed(sext_ln67_28_fu_995_p1) + $signed(add_ln67_24_fu_981_p2));

assign temp_7_fu_1029_p2 = ($signed(sext_ln67_31_fu_1025_p1) + $signed(add_ln67_28_fu_1011_p2));

assign temp_fu_681_p2 = ($signed(sext_ln67_10_fu_677_p1) + $signed(add_ln67_fu_663_p2));

assign trunc_ln67_1_fu_435_p1 = acc_1[15:0];

assign trunc_ln67_2_fu_449_p1 = acc_2[15:0];

assign trunc_ln67_3_fu_463_p1 = acc_3[15:0];

assign trunc_ln67_4_fu_477_p1 = acc_4[15:0];

assign trunc_ln67_5_fu_491_p1 = acc_5[15:0];

assign trunc_ln67_6_fu_505_p1 = acc_6[15:0];

assign trunc_ln67_7_fu_519_p1 = acc_7[15:0];

assign trunc_ln67_fu_421_p1 = acc_0[15:0];

endmodule //array_io
