// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_io_array_io,hls_ip_2022_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.581000,HLS_SYN_LAT=10,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=867,HLS_SYN_LUT=2135,HLS_VERSION=2022_1}" *)

module array_io (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_o_0_din,
        d_o_0_full_n,
        d_o_0_write,
        d_o_1_din,
        d_o_1_full_n,
        d_o_1_write,
        d_o_2_din,
        d_o_2_full_n,
        d_o_2_write,
        d_o_3_din,
        d_o_3_full_n,
        d_o_3_write,
        d_i_0_address0,
        d_i_0_ce0,
        d_i_0_q0,
        d_i_0_address1,
        d_i_0_ce1,
        d_i_0_q1,
        d_i_1_address0,
        d_i_1_ce0,
        d_i_1_q0,
        d_i_1_address1,
        d_i_1_ce1,
        d_i_1_q1
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] d_o_0_din;
input   d_o_0_full_n;
output   d_o_0_write;
output  [15:0] d_o_1_din;
input   d_o_1_full_n;
output   d_o_1_write;
output  [15:0] d_o_2_din;
input   d_o_2_full_n;
output   d_o_2_write;
output  [15:0] d_o_3_din;
input   d_o_3_full_n;
output   d_o_3_write;
output  [3:0] d_i_0_address0;
output   d_i_0_ce0;
input  [15:0] d_i_0_q0;
output  [3:0] d_i_0_address1;
output   d_i_0_ce1;
input  [15:0] d_i_0_q1;
output  [3:0] d_i_1_address0;
output   d_i_1_ce0;
input  [15:0] d_i_1_q0;
output  [3:0] d_i_1_address1;
output   d_i_1_ce1;
input  [15:0] d_i_1_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] d_o_0_din;
reg d_o_0_write;
reg[15:0] d_o_1_din;
reg d_o_1_write;
reg[15:0] d_o_2_din;
reg d_o_2_write;
reg[15:0] d_o_3_din;
reg d_o_3_write;
reg[3:0] d_i_0_address0;
reg d_i_0_ce0;
reg[3:0] d_i_0_address1;
reg d_i_0_ce1;
reg[3:0] d_i_1_address0;
reg d_i_1_ce0;
reg[3:0] d_i_1_address1;
reg d_i_1_ce1;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] acc_0;
reg   [31:0] acc_1;
reg   [31:0] acc_2;
reg   [31:0] acc_3;
reg   [31:0] acc_4;
reg   [31:0] acc_5;
reg   [31:0] acc_6;
reg   [31:0] acc_7;
reg    d_o_0_blk_n;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    d_o_1_blk_n;
reg    d_o_2_blk_n;
reg    d_o_3_blk_n;
reg  signed [15:0] reg_414;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_block_state4;
reg    ap_block_state5;
reg    ap_block_state6;
reg    ap_block_state7;
reg    ap_block_state8;
reg    ap_block_state9;
reg  signed [15:0] reg_418;
reg  signed [15:0] reg_422;
reg  signed [15:0] reg_426;
reg  signed [15:0] reg_430;
wire   [15:0] add_ln69_fu_442_p2;
reg   [15:0] add_ln69_reg_1121;
wire   [16:0] add_ln67_1_fu_456_p2;
reg   [16:0] add_ln67_1_reg_1142;
wire   [15:0] add_ln69_1_fu_474_p2;
reg   [15:0] add_ln69_1_reg_1155;
wire   [15:0] add_ln69_8_fu_484_p2;
reg   [15:0] add_ln69_8_reg_1166;
wire   [15:0] add_ln69_16_fu_489_p2;
reg   [15:0] add_ln69_16_reg_1176;
wire   [16:0] add_ln67_5_fu_533_p2;
reg   [16:0] add_ln67_5_reg_1187;
wire   [15:0] add_ln69_2_fu_551_p2;
reg   [15:0] add_ln69_2_reg_1200;
wire   [15:0] add_ln69_9_fu_561_p2;
reg   [15:0] add_ln69_9_reg_1211;
wire   [15:0] add_ln69_17_fu_566_p2;
reg   [15:0] add_ln69_17_reg_1221;
wire   [16:0] add_ln67_9_fu_616_p2;
reg   [16:0] add_ln67_9_reg_1232;
wire   [15:0] add_ln69_3_fu_634_p2;
reg   [15:0] add_ln69_3_reg_1245;
wire   [15:0] add_ln69_10_fu_644_p2;
reg   [15:0] add_ln69_10_reg_1256;
wire   [15:0] add_ln69_18_fu_649_p2;
reg   [15:0] add_ln69_18_reg_1266;
wire   [16:0] add_ln67_13_fu_699_p2;
reg   [16:0] add_ln67_13_reg_1277;
wire   [15:0] add_ln69_4_fu_717_p2;
reg   [15:0] add_ln69_4_reg_1290;
wire   [15:0] add_ln69_11_fu_727_p2;
reg   [15:0] add_ln69_11_reg_1301;
wire   [15:0] add_ln69_19_fu_732_p2;
reg   [15:0] add_ln69_19_reg_1311;
wire   [16:0] add_ln67_17_fu_782_p2;
reg   [16:0] add_ln67_17_reg_1322;
wire   [15:0] add_ln69_5_fu_800_p2;
reg   [15:0] add_ln69_5_reg_1335;
wire   [15:0] add_ln69_12_fu_810_p2;
reg   [15:0] add_ln69_12_reg_1346;
wire   [15:0] add_ln69_20_fu_815_p2;
reg   [15:0] add_ln69_20_reg_1356;
wire   [16:0] add_ln67_21_fu_865_p2;
reg   [16:0] add_ln67_21_reg_1367;
wire   [15:0] add_ln69_6_fu_883_p2;
reg   [15:0] add_ln69_6_reg_1380;
wire   [15:0] add_ln69_13_fu_893_p2;
reg   [15:0] add_ln69_13_reg_1391;
wire   [15:0] add_ln69_21_fu_898_p2;
reg   [15:0] add_ln69_21_reg_1401;
wire   [16:0] add_ln67_25_fu_948_p2;
reg   [16:0] add_ln67_25_reg_1412;
wire   [15:0] add_ln69_7_fu_966_p2;
reg   [15:0] add_ln69_7_reg_1425;
wire   [15:0] add_ln69_14_fu_976_p2;
reg   [15:0] add_ln69_14_reg_1431;
wire   [15:0] add_ln69_22_fu_981_p2;
reg   [15:0] add_ln69_22_reg_1436;
wire   [16:0] add_ln67_29_fu_1031_p2;
reg   [16:0] add_ln67_29_reg_1442;
wire   [15:0] add_ln69_15_fu_1045_p2;
reg   [15:0] add_ln69_15_reg_1447;
wire   [15:0] add_ln69_23_fu_1050_p2;
reg   [15:0] add_ln69_23_reg_1452;
wire   [31:0] temp_fu_517_p2;
wire   [31:0] temp_1_fu_600_p2;
wire   [31:0] temp_2_fu_683_p2;
wire   [31:0] temp_3_fu_766_p2;
wire   [31:0] temp_4_fu_849_p2;
wire   [31:0] temp_5_fu_932_p2;
wire   [31:0] temp_6_fu_1015_p2;
wire   [31:0] temp_7_fu_1080_p2;
reg    ap_block_state10;
reg    ap_block_state11;
wire   [15:0] add_ln69_24_fu_576_p2;
wire   [15:0] add_ln69_25_fu_659_p2;
wire   [15:0] add_ln69_26_fu_742_p2;
wire   [15:0] add_ln69_27_fu_825_p2;
wire   [15:0] add_ln69_28_fu_908_p2;
wire   [15:0] add_ln69_29_fu_991_p2;
wire   [15:0] add_ln69_30_fu_1056_p2;
wire   [15:0] add_ln69_31_fu_1092_p2;
wire  signed [15:0] add_ln69_fu_442_p0;
wire   [15:0] trunc_ln67_fu_438_p1;
wire  signed [15:0] sext_ln69_8_fu_448_p0;
wire  signed [15:0] sext_ln67_8_fu_452_p0;
wire  signed [16:0] sext_ln69_8_fu_448_p1;
wire  signed [16:0] sext_ln67_8_fu_452_p1;
wire  signed [15:0] add_ln69_1_fu_474_p0;
wire   [15:0] trunc_ln67_1_fu_470_p1;
wire  signed [15:0] sext_ln69_9_fu_495_p0;
wire  signed [31:0] sext_ln67_fu_462_p1;
wire  signed [17:0] sext_ln67_9_fu_504_p1;
wire  signed [17:0] sext_ln69_fu_480_p1;
wire   [17:0] add_ln67_2_fu_507_p2;
wire  signed [31:0] sext_ln67_10_fu_513_p1;
wire   [31:0] add_ln67_fu_499_p2;
wire  signed [15:0] sext_ln67_11_fu_529_p0;
wire  signed [16:0] sext_ln69_9_fu_495_p1;
wire  signed [16:0] sext_ln67_11_fu_529_p1;
wire  signed [15:0] add_ln69_2_fu_551_p0;
wire   [15:0] trunc_ln67_2_fu_547_p1;
wire  signed [15:0] sext_ln69_10_fu_572_p0;
wire  signed [31:0] sext_ln67_1_fu_539_p1;
wire  signed [17:0] sext_ln67_12_fu_587_p1;
wire  signed [17:0] sext_ln69_1_fu_557_p1;
wire   [17:0] add_ln67_6_fu_590_p2;
wire  signed [31:0] sext_ln67_13_fu_596_p1;
wire   [31:0] add_ln67_4_fu_582_p2;
wire  signed [15:0] sext_ln67_14_fu_612_p0;
wire  signed [16:0] sext_ln69_10_fu_572_p1;
wire  signed [16:0] sext_ln67_14_fu_612_p1;
wire  signed [15:0] add_ln69_3_fu_634_p0;
wire   [15:0] trunc_ln67_3_fu_630_p1;
wire  signed [15:0] sext_ln69_11_fu_655_p0;
wire  signed [31:0] sext_ln67_2_fu_622_p1;
wire  signed [17:0] sext_ln67_15_fu_670_p1;
wire  signed [17:0] sext_ln69_2_fu_640_p1;
wire   [17:0] add_ln67_10_fu_673_p2;
wire  signed [31:0] sext_ln67_16_fu_679_p1;
wire   [31:0] add_ln67_8_fu_665_p2;
wire  signed [15:0] sext_ln67_17_fu_695_p0;
wire  signed [16:0] sext_ln69_11_fu_655_p1;
wire  signed [16:0] sext_ln67_17_fu_695_p1;
wire  signed [15:0] add_ln69_4_fu_717_p0;
wire   [15:0] trunc_ln67_4_fu_713_p1;
wire  signed [15:0] sext_ln69_12_fu_738_p0;
wire  signed [31:0] sext_ln67_3_fu_705_p1;
wire  signed [17:0] sext_ln67_18_fu_753_p1;
wire  signed [17:0] sext_ln69_3_fu_723_p1;
wire   [17:0] add_ln67_14_fu_756_p2;
wire  signed [31:0] sext_ln67_19_fu_762_p1;
wire   [31:0] add_ln67_12_fu_748_p2;
wire  signed [15:0] sext_ln67_20_fu_778_p0;
wire  signed [16:0] sext_ln69_12_fu_738_p1;
wire  signed [16:0] sext_ln67_20_fu_778_p1;
wire  signed [15:0] add_ln69_5_fu_800_p0;
wire   [15:0] trunc_ln67_5_fu_796_p1;
wire  signed [15:0] sext_ln69_13_fu_821_p0;
wire  signed [31:0] sext_ln67_4_fu_788_p1;
wire  signed [17:0] sext_ln67_21_fu_836_p1;
wire  signed [17:0] sext_ln69_4_fu_806_p1;
wire   [17:0] add_ln67_18_fu_839_p2;
wire  signed [31:0] sext_ln67_22_fu_845_p1;
wire   [31:0] add_ln67_16_fu_831_p2;
wire  signed [15:0] sext_ln67_23_fu_861_p0;
wire  signed [16:0] sext_ln69_13_fu_821_p1;
wire  signed [16:0] sext_ln67_23_fu_861_p1;
wire  signed [15:0] add_ln69_6_fu_883_p0;
wire   [15:0] trunc_ln67_6_fu_879_p1;
wire  signed [15:0] sext_ln69_14_fu_904_p0;
wire  signed [31:0] sext_ln67_5_fu_871_p1;
wire  signed [17:0] sext_ln67_24_fu_919_p1;
wire  signed [17:0] sext_ln69_5_fu_889_p1;
wire   [17:0] add_ln67_22_fu_922_p2;
wire  signed [31:0] sext_ln67_25_fu_928_p1;
wire   [31:0] add_ln67_20_fu_914_p2;
wire  signed [15:0] sext_ln67_26_fu_944_p0;
wire  signed [16:0] sext_ln69_14_fu_904_p1;
wire  signed [16:0] sext_ln67_26_fu_944_p1;
wire  signed [15:0] add_ln69_7_fu_966_p0;
wire   [15:0] trunc_ln67_7_fu_962_p1;
wire  signed [15:0] sext_ln69_15_fu_987_p0;
wire  signed [31:0] sext_ln67_6_fu_954_p1;
wire  signed [17:0] sext_ln67_27_fu_1002_p1;
wire  signed [17:0] sext_ln69_6_fu_972_p1;
wire   [17:0] add_ln67_26_fu_1005_p2;
wire  signed [31:0] sext_ln67_28_fu_1011_p1;
wire   [31:0] add_ln67_24_fu_997_p2;
wire  signed [15:0] sext_ln67_29_fu_1027_p0;
wire  signed [16:0] sext_ln69_15_fu_987_p1;
wire  signed [16:0] sext_ln67_29_fu_1027_p1;
wire  signed [31:0] sext_ln67_7_fu_1037_p1;
wire  signed [17:0] sext_ln67_30_fu_1067_p1;
wire  signed [17:0] sext_ln69_7_fu_1041_p1;
wire   [17:0] add_ln67_30_fu_1070_p2;
wire  signed [31:0] sext_ln67_31_fu_1076_p1;
wire   [31:0] add_ln67_28_fu_1062_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_condition_144;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 acc_0 = 32'd0;
#0 acc_1 = 32'd0;
#0 acc_2 = 32'd0;
#0 acc_3 = 32'd0;
#0 acc_4 = 32'd0;
#0 acc_5 = 32'd0;
#0 acc_6 = 32'd0;
#0 acc_7 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_0 <= temp_fu_517_p2;
        add_ln67_5_reg_1187 <= add_ln67_5_fu_533_p2;
        add_ln69_16_reg_1176 <= add_ln69_16_fu_489_p2;
        add_ln69_1_reg_1155 <= add_ln69_1_fu_474_p2;
        add_ln69_8_reg_1166 <= add_ln69_8_fu_484_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_1 <= temp_1_fu_600_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_2 <= temp_2_fu_683_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_3 <= temp_3_fu_766_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        acc_4 <= temp_4_fu_849_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        acc_5 <= temp_5_fu_932_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
        acc_6 <= temp_6_fu_1015_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_7 <= temp_7_fu_1080_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln67_13_reg_1277 <= add_ln67_13_fu_699_p2;
        add_ln69_10_reg_1256 <= add_ln69_10_fu_644_p2;
        add_ln69_18_reg_1266 <= add_ln69_18_fu_649_p2;
        add_ln69_3_reg_1245 <= add_ln69_3_fu_634_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln67_17_reg_1322 <= add_ln67_17_fu_782_p2;
        add_ln69_11_reg_1301 <= add_ln69_11_fu_727_p2;
        add_ln69_19_reg_1311 <= add_ln69_19_fu_732_p2;
        add_ln69_4_reg_1290 <= add_ln69_4_fu_717_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln67_1_reg_1142 <= add_ln67_1_fu_456_p2;
        add_ln69_reg_1121 <= add_ln69_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln67_21_reg_1367 <= add_ln67_21_fu_865_p2;
        add_ln69_12_reg_1346 <= add_ln69_12_fu_810_p2;
        add_ln69_20_reg_1356 <= add_ln69_20_fu_815_p2;
        add_ln69_5_reg_1335 <= add_ln69_5_fu_800_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln67_25_reg_1412 <= add_ln67_25_fu_948_p2;
        add_ln69_13_reg_1391 <= add_ln69_13_fu_893_p2;
        add_ln69_21_reg_1401 <= add_ln69_21_fu_898_p2;
        add_ln69_6_reg_1380 <= add_ln69_6_fu_883_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln67_29_reg_1442 <= add_ln67_29_fu_1031_p2;
        add_ln69_14_reg_1431 <= add_ln69_14_fu_976_p2;
        add_ln69_22_reg_1436 <= add_ln69_22_fu_981_p2;
        add_ln69_7_reg_1425 <= add_ln69_7_fu_966_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln67_9_reg_1232 <= add_ln67_9_fu_616_p2;
        add_ln69_17_reg_1221 <= add_ln69_17_fu_566_p2;
        add_ln69_2_reg_1200 <= add_ln69_2_fu_551_p2;
        add_ln69_9_reg_1211 <= add_ln69_9_fu_561_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln69_15_reg_1447 <= add_ln69_15_fu_1045_p2;
        add_ln69_23_reg_1452 <= add_ln69_23_fu_1050_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        reg_414 <= d_i_0_q1;
        reg_418 <= d_i_0_q0;
        reg_422 <= d_i_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        reg_426 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)))) begin
        reg_430 <= d_i_1_q0;
    end
end

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_0_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_0_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_0_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_0_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_0_address0 = 64'd8;
    end else begin
        d_i_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_0_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_0_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_0_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_0_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_0_address1 = 64'd0;
    end else begin
        d_i_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_i_0_ce0 = 1'b1;
    end else begin
        d_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_i_0_ce1 = 1'b1;
    end else begin
        d_i_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_1_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_1_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_1_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_1_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_1_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_1_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_1_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_1_address0 = 64'd8;
    end else begin
        d_i_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_1_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_1_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_1_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_1_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_1_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_1_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_1_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_1_address1 = 64'd0;
    end else begin
        d_i_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_i_1_ce0 = 1'b1;
    end else begin
        d_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_i_1_ce1 = 1'b1;
    end else begin
        d_i_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        d_o_0_blk_n = d_o_0_full_n;
    end else begin
        d_o_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_0_din = add_ln69_7_reg_1425;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_0_din = add_ln69_6_reg_1380;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_0_din = add_ln69_5_reg_1335;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_0_din = add_ln69_4_reg_1290;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_0_din = add_ln69_3_reg_1245;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_0_din = add_ln69_2_reg_1200;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_0_din = add_ln69_1_reg_1155;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_0_din = add_ln69_reg_1121;
        end else begin
            d_o_0_din = 'bx;
        end
    end else begin
        d_o_0_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_o_0_write = 1'b1;
    end else begin
        d_o_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        d_o_1_blk_n = d_o_1_full_n;
    end else begin
        d_o_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_1_din = add_ln69_15_reg_1447;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_1_din = add_ln69_14_reg_1431;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_1_din = add_ln69_13_reg_1391;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_1_din = add_ln69_12_reg_1346;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_1_din = add_ln69_11_reg_1301;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_1_din = add_ln69_10_reg_1256;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_1_din = add_ln69_9_reg_1211;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_1_din = add_ln69_8_reg_1166;
        end else begin
            d_o_1_din = 'bx;
        end
    end else begin
        d_o_1_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_o_1_write = 1'b1;
    end else begin
        d_o_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        d_o_2_blk_n = d_o_2_full_n;
    end else begin
        d_o_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_2_din = add_ln69_23_reg_1452;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_2_din = add_ln69_22_reg_1436;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_2_din = add_ln69_21_reg_1401;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_2_din = add_ln69_20_reg_1356;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_2_din = add_ln69_19_reg_1311;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_2_din = add_ln69_18_reg_1266;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_2_din = add_ln69_17_reg_1221;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_2_din = add_ln69_16_reg_1176;
        end else begin
            d_o_2_din = 'bx;
        end
    end else begin
        d_o_2_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_o_2_write = 1'b1;
    end else begin
        d_o_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        d_o_3_blk_n = d_o_3_full_n;
    end else begin
        d_o_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_3_din = add_ln69_31_fu_1092_p2;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_3_din = add_ln69_30_fu_1056_p2;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_3_din = add_ln69_29_fu_991_p2;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_3_din = add_ln69_28_fu_908_p2;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_3_din = add_ln69_27_fu_825_p2;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_3_din = add_ln69_26_fu_742_p2;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_3_din = add_ln69_25_fu_659_p2;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_3_din = add_ln69_24_fu_576_p2;
        end else begin
            d_o_3_din = 'bx;
        end
    end else begin
        d_o_3_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)) | (~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)))) begin
        d_o_3_write = 1'b1;
    end else begin
        d_o_3_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_10_fu_673_p2 = ($signed(sext_ln67_15_fu_670_p1) + $signed(sext_ln69_2_fu_640_p1));

assign add_ln67_12_fu_748_p2 = ($signed(acc_3) + $signed(sext_ln67_3_fu_705_p1));

assign add_ln67_13_fu_699_p2 = ($signed(sext_ln69_11_fu_655_p1) + $signed(sext_ln67_17_fu_695_p1));

assign add_ln67_14_fu_756_p2 = ($signed(sext_ln67_18_fu_753_p1) + $signed(sext_ln69_3_fu_723_p1));

assign add_ln67_16_fu_831_p2 = ($signed(acc_4) + $signed(sext_ln67_4_fu_788_p1));

assign add_ln67_17_fu_782_p2 = ($signed(sext_ln69_12_fu_738_p1) + $signed(sext_ln67_20_fu_778_p1));

assign add_ln67_18_fu_839_p2 = ($signed(sext_ln67_21_fu_836_p1) + $signed(sext_ln69_4_fu_806_p1));

assign add_ln67_1_fu_456_p2 = ($signed(sext_ln69_8_fu_448_p1) + $signed(sext_ln67_8_fu_452_p1));

assign add_ln67_20_fu_914_p2 = ($signed(acc_5) + $signed(sext_ln67_5_fu_871_p1));

assign add_ln67_21_fu_865_p2 = ($signed(sext_ln69_13_fu_821_p1) + $signed(sext_ln67_23_fu_861_p1));

assign add_ln67_22_fu_922_p2 = ($signed(sext_ln67_24_fu_919_p1) + $signed(sext_ln69_5_fu_889_p1));

assign add_ln67_24_fu_997_p2 = ($signed(acc_6) + $signed(sext_ln67_6_fu_954_p1));

assign add_ln67_25_fu_948_p2 = ($signed(sext_ln69_14_fu_904_p1) + $signed(sext_ln67_26_fu_944_p1));

assign add_ln67_26_fu_1005_p2 = ($signed(sext_ln67_27_fu_1002_p1) + $signed(sext_ln69_6_fu_972_p1));

assign add_ln67_28_fu_1062_p2 = ($signed(acc_7) + $signed(sext_ln67_7_fu_1037_p1));

assign add_ln67_29_fu_1031_p2 = ($signed(sext_ln69_15_fu_987_p1) + $signed(sext_ln67_29_fu_1027_p1));

assign add_ln67_2_fu_507_p2 = ($signed(sext_ln67_9_fu_504_p1) + $signed(sext_ln69_fu_480_p1));

assign add_ln67_30_fu_1070_p2 = ($signed(sext_ln67_30_fu_1067_p1) + $signed(sext_ln69_7_fu_1041_p1));

assign add_ln67_4_fu_582_p2 = ($signed(acc_1) + $signed(sext_ln67_1_fu_539_p1));

assign add_ln67_5_fu_533_p2 = ($signed(sext_ln69_9_fu_495_p1) + $signed(sext_ln67_11_fu_529_p1));

assign add_ln67_6_fu_590_p2 = ($signed(sext_ln67_12_fu_587_p1) + $signed(sext_ln69_1_fu_557_p1));

assign add_ln67_8_fu_665_p2 = ($signed(acc_2) + $signed(sext_ln67_2_fu_622_p1));

assign add_ln67_9_fu_616_p2 = ($signed(sext_ln69_10_fu_572_p1) + $signed(sext_ln67_14_fu_612_p1));

assign add_ln67_fu_499_p2 = ($signed(acc_0) + $signed(sext_ln67_fu_462_p1));

assign add_ln69_10_fu_644_p2 = ($signed(reg_418) + $signed(add_ln69_2_reg_1200));

assign add_ln69_11_fu_727_p2 = ($signed(reg_418) + $signed(add_ln69_3_reg_1245));

assign add_ln69_12_fu_810_p2 = ($signed(reg_418) + $signed(add_ln69_4_reg_1290));

assign add_ln69_13_fu_893_p2 = ($signed(reg_418) + $signed(add_ln69_5_reg_1335));

assign add_ln69_14_fu_976_p2 = ($signed(reg_418) + $signed(add_ln69_6_reg_1380));

assign add_ln69_15_fu_1045_p2 = ($signed(reg_418) + $signed(add_ln69_7_reg_1425));

assign add_ln69_16_fu_489_p2 = ($signed(reg_422) + $signed(add_ln69_8_fu_484_p2));

assign add_ln69_17_fu_566_p2 = ($signed(reg_422) + $signed(add_ln69_9_fu_561_p2));

assign add_ln69_18_fu_649_p2 = ($signed(reg_422) + $signed(add_ln69_10_fu_644_p2));

assign add_ln69_19_fu_732_p2 = ($signed(reg_422) + $signed(add_ln69_11_fu_727_p2));

assign add_ln69_1_fu_474_p0 = d_i_0_q1;

assign add_ln69_1_fu_474_p2 = ($signed(add_ln69_1_fu_474_p0) + $signed(trunc_ln67_1_fu_470_p1));

assign add_ln69_20_fu_815_p2 = ($signed(reg_422) + $signed(add_ln69_12_fu_810_p2));

assign add_ln69_21_fu_898_p2 = ($signed(reg_422) + $signed(add_ln69_13_fu_893_p2));

assign add_ln69_22_fu_981_p2 = ($signed(reg_422) + $signed(add_ln69_14_fu_976_p2));

assign add_ln69_23_fu_1050_p2 = ($signed(reg_422) + $signed(add_ln69_15_fu_1045_p2));

assign add_ln69_24_fu_576_p2 = ($signed(reg_426) + $signed(add_ln69_16_reg_1176));

assign add_ln69_25_fu_659_p2 = ($signed(reg_430) + $signed(add_ln69_17_reg_1221));

assign add_ln69_26_fu_742_p2 = ($signed(reg_426) + $signed(add_ln69_18_reg_1266));

assign add_ln69_27_fu_825_p2 = ($signed(reg_430) + $signed(add_ln69_19_reg_1311));

assign add_ln69_28_fu_908_p2 = ($signed(reg_426) + $signed(add_ln69_20_reg_1356));

assign add_ln69_29_fu_991_p2 = ($signed(reg_430) + $signed(add_ln69_21_reg_1401));

assign add_ln69_2_fu_551_p0 = d_i_0_q1;

assign add_ln69_2_fu_551_p2 = ($signed(add_ln69_2_fu_551_p0) + $signed(trunc_ln67_2_fu_547_p1));

assign add_ln69_30_fu_1056_p2 = ($signed(reg_426) + $signed(add_ln69_22_reg_1436));

assign add_ln69_31_fu_1092_p2 = ($signed(reg_430) + $signed(add_ln69_23_reg_1452));

assign add_ln69_3_fu_634_p0 = d_i_0_q1;

assign add_ln69_3_fu_634_p2 = ($signed(add_ln69_3_fu_634_p0) + $signed(trunc_ln67_3_fu_630_p1));

assign add_ln69_4_fu_717_p0 = d_i_0_q1;

assign add_ln69_4_fu_717_p2 = ($signed(add_ln69_4_fu_717_p0) + $signed(trunc_ln67_4_fu_713_p1));

assign add_ln69_5_fu_800_p0 = d_i_0_q1;

assign add_ln69_5_fu_800_p2 = ($signed(add_ln69_5_fu_800_p0) + $signed(trunc_ln67_5_fu_796_p1));

assign add_ln69_6_fu_883_p0 = d_i_0_q1;

assign add_ln69_6_fu_883_p2 = ($signed(add_ln69_6_fu_883_p0) + $signed(trunc_ln67_6_fu_879_p1));

assign add_ln69_7_fu_966_p0 = d_i_0_q1;

assign add_ln69_7_fu_966_p2 = ($signed(add_ln69_7_fu_966_p0) + $signed(trunc_ln67_7_fu_962_p1));

assign add_ln69_8_fu_484_p2 = ($signed(reg_418) + $signed(add_ln69_reg_1121));

assign add_ln69_9_fu_561_p2 = ($signed(reg_418) + $signed(add_ln69_1_reg_1155));

assign add_ln69_fu_442_p0 = d_i_0_q1;

assign add_ln69_fu_442_p2 = ($signed(add_ln69_fu_442_p0) + $signed(trunc_ln67_fu_438_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state11 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state8 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state9 = ((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_144 = ~((d_o_3_full_n == 1'b0) | (d_o_2_full_n == 1'b0) | (d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

assign sext_ln67_10_fu_513_p1 = $signed(add_ln67_2_fu_507_p2);

assign sext_ln67_11_fu_529_p0 = d_i_1_q0;

assign sext_ln67_11_fu_529_p1 = sext_ln67_11_fu_529_p0;

assign sext_ln67_12_fu_587_p1 = $signed(add_ln67_5_reg_1187);

assign sext_ln67_13_fu_596_p1 = $signed(add_ln67_6_fu_590_p2);

assign sext_ln67_14_fu_612_p0 = d_i_1_q0;

assign sext_ln67_14_fu_612_p1 = sext_ln67_14_fu_612_p0;

assign sext_ln67_15_fu_670_p1 = $signed(add_ln67_9_reg_1232);

assign sext_ln67_16_fu_679_p1 = $signed(add_ln67_10_fu_673_p2);

assign sext_ln67_17_fu_695_p0 = d_i_1_q0;

assign sext_ln67_17_fu_695_p1 = sext_ln67_17_fu_695_p0;

assign sext_ln67_18_fu_753_p1 = $signed(add_ln67_13_reg_1277);

assign sext_ln67_19_fu_762_p1 = $signed(add_ln67_14_fu_756_p2);

assign sext_ln67_1_fu_539_p1 = reg_414;

assign sext_ln67_20_fu_778_p0 = d_i_1_q0;

assign sext_ln67_20_fu_778_p1 = sext_ln67_20_fu_778_p0;

assign sext_ln67_21_fu_836_p1 = $signed(add_ln67_17_reg_1322);

assign sext_ln67_22_fu_845_p1 = $signed(add_ln67_18_fu_839_p2);

assign sext_ln67_23_fu_861_p0 = d_i_1_q0;

assign sext_ln67_23_fu_861_p1 = sext_ln67_23_fu_861_p0;

assign sext_ln67_24_fu_919_p1 = $signed(add_ln67_21_reg_1367);

assign sext_ln67_25_fu_928_p1 = $signed(add_ln67_22_fu_922_p2);

assign sext_ln67_26_fu_944_p0 = d_i_1_q0;

assign sext_ln67_26_fu_944_p1 = sext_ln67_26_fu_944_p0;

assign sext_ln67_27_fu_1002_p1 = $signed(add_ln67_25_reg_1412);

assign sext_ln67_28_fu_1011_p1 = $signed(add_ln67_26_fu_1005_p2);

assign sext_ln67_29_fu_1027_p0 = d_i_1_q0;

assign sext_ln67_29_fu_1027_p1 = sext_ln67_29_fu_1027_p0;

assign sext_ln67_2_fu_622_p1 = reg_414;

assign sext_ln67_30_fu_1067_p1 = $signed(add_ln67_29_reg_1442);

assign sext_ln67_31_fu_1076_p1 = $signed(add_ln67_30_fu_1070_p2);

assign sext_ln67_3_fu_705_p1 = reg_414;

assign sext_ln67_4_fu_788_p1 = reg_414;

assign sext_ln67_5_fu_871_p1 = reg_414;

assign sext_ln67_6_fu_954_p1 = reg_414;

assign sext_ln67_7_fu_1037_p1 = reg_414;

assign sext_ln67_8_fu_452_p0 = d_i_1_q0;

assign sext_ln67_8_fu_452_p1 = sext_ln67_8_fu_452_p0;

assign sext_ln67_9_fu_504_p1 = $signed(add_ln67_1_reg_1142);

assign sext_ln67_fu_462_p1 = reg_414;

assign sext_ln69_10_fu_572_p0 = d_i_1_q1;

assign sext_ln69_10_fu_572_p1 = sext_ln69_10_fu_572_p0;

assign sext_ln69_11_fu_655_p0 = d_i_1_q1;

assign sext_ln69_11_fu_655_p1 = sext_ln69_11_fu_655_p0;

assign sext_ln69_12_fu_738_p0 = d_i_1_q1;

assign sext_ln69_12_fu_738_p1 = sext_ln69_12_fu_738_p0;

assign sext_ln69_13_fu_821_p0 = d_i_1_q1;

assign sext_ln69_13_fu_821_p1 = sext_ln69_13_fu_821_p0;

assign sext_ln69_14_fu_904_p0 = d_i_1_q1;

assign sext_ln69_14_fu_904_p1 = sext_ln69_14_fu_904_p0;

assign sext_ln69_15_fu_987_p0 = d_i_1_q1;

assign sext_ln69_15_fu_987_p1 = sext_ln69_15_fu_987_p0;

assign sext_ln69_1_fu_557_p1 = reg_418;

assign sext_ln69_2_fu_640_p1 = reg_418;

assign sext_ln69_3_fu_723_p1 = reg_418;

assign sext_ln69_4_fu_806_p1 = reg_418;

assign sext_ln69_5_fu_889_p1 = reg_418;

assign sext_ln69_6_fu_972_p1 = reg_418;

assign sext_ln69_7_fu_1041_p1 = reg_418;

assign sext_ln69_8_fu_448_p0 = d_i_1_q1;

assign sext_ln69_8_fu_448_p1 = sext_ln69_8_fu_448_p0;

assign sext_ln69_9_fu_495_p0 = d_i_1_q1;

assign sext_ln69_9_fu_495_p1 = sext_ln69_9_fu_495_p0;

assign sext_ln69_fu_480_p1 = reg_418;

assign temp_1_fu_600_p2 = ($signed(sext_ln67_13_fu_596_p1) + $signed(add_ln67_4_fu_582_p2));

assign temp_2_fu_683_p2 = ($signed(sext_ln67_16_fu_679_p1) + $signed(add_ln67_8_fu_665_p2));

assign temp_3_fu_766_p2 = ($signed(sext_ln67_19_fu_762_p1) + $signed(add_ln67_12_fu_748_p2));

assign temp_4_fu_849_p2 = ($signed(sext_ln67_22_fu_845_p1) + $signed(add_ln67_16_fu_831_p2));

assign temp_5_fu_932_p2 = ($signed(sext_ln67_25_fu_928_p1) + $signed(add_ln67_20_fu_914_p2));

assign temp_6_fu_1015_p2 = ($signed(sext_ln67_28_fu_1011_p1) + $signed(add_ln67_24_fu_997_p2));

assign temp_7_fu_1080_p2 = ($signed(sext_ln67_31_fu_1076_p1) + $signed(add_ln67_28_fu_1062_p2));

assign temp_fu_517_p2 = ($signed(sext_ln67_10_fu_513_p1) + $signed(add_ln67_fu_499_p2));

assign trunc_ln67_1_fu_470_p1 = acc_1[15:0];

assign trunc_ln67_2_fu_547_p1 = acc_2[15:0];

assign trunc_ln67_3_fu_630_p1 = acc_3[15:0];

assign trunc_ln67_4_fu_713_p1 = acc_4[15:0];

assign trunc_ln67_5_fu_796_p1 = acc_5[15:0];

assign trunc_ln67_6_fu_879_p1 = acc_6[15:0];

assign trunc_ln67_7_fu_962_p1 = acc_7[15:0];

assign trunc_ln67_fu_438_p1 = acc_0[15:0];

endmodule //array_io
